.github/workflows/ci.yml, .vscode/launch.json, Tiltfile, etc/aa-bundler/aa-bundler.config.json, keys/.gitignore, packages/app/features/onboarding/__snapshots__/screen.test.tsx.snap, packages/app/features/onboarding/index.test.ts, packages/app/features/onboarding/screen.test.tsx, packages/app/features/onboarding/screen.tsx, packages/app/jest.config.ts, packages/app/package.json, packages/app/utils/passkeys.ts, packages/app/utils/viem/client.ts, packages/playwright/tests/onboarding.logged-in.spec.ts, packages/webauthn-authenticator/src/preload.ts, packages/webauthn-authenticator/src/types.ts, packages/webauthn-authenticator/src/utils.ts, packages/webauthn-authenticator/src/web-authenticator.ts, yarn.lock
- adds test for creating accounts
- starts userop bundler integration
=> more onboarding

CONTRIBUTING.md
Add some instructions for running anvil for mainnet and base on the expected dev ports
=> Add Anvil Node contribution docs

Caddyfile.dev, Tiltfile
=> add otterscan resources

apps/distributor/src/distributor.ts, packages/app/components/sidebar/HomeSideBar.tsx, packages/app/features/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/activity/screen.tsx, packages/app/features/home/screen.tsx, packages/app/features/onboarding/screen.tsx, packages/app/provider/tag-search/TagSearchProvider.tsx, packages/ui/src/components/FormWrapper.tsx, supabase/migrations/20240116215010_create_tag_search_function.sql
fix distributor after updating row limit
=> fixes and tweaks for activity and form

apps/next/pages/leaderboard.tsx, packages/app/components/sidebar/HomeSideBar.tsx, packages/app/features/leaderboard/screen.tsx
Figma Link: https://www.figma.com/file/k7ct2aqK1zUvZripOWtW8h/send-landing?type=design&node-id=1399-4553&mode=design&t=mlAvUORr9sxSb8d8-4
=> Leaderboard Styles

apps/next/pages/distributions.tsx, packages/app/features/distributions/components/DistributionsTable.tsx, packages/app/features/distributions/components/distribution-stat-cards.tsx, packages/app/features/distributions/screen.tsx, packages/app/features/home/layout.web.tsx
Notably this PR is missing the inset shadow on the countdown components. Inset shadow is hard to do in react native/tamagui, so it will be dedicated to a seperate PR
[Here is the figma this PR is based on](https://www.figma.com/file/k7ct2aqK1zUvZripOWtW8h/send-landing?type=design&node-id=1399-4453&mode=design&t=JRPvN6cLdoUkLS3N-4)
=> Update Distribution Page styling

packages/app/features/auth/components/VerifyCode.tsx, packages/app/features/auth/sign-in-form.tsx, packages/app/features/auth/sign-in-screen.tsx
There are probably two ways to improve this
either:
1. Use url query params to manage pages inside sign-in
2. Use a reducer and context to manage the pages>
=> Pages for Mobile Signin

apps/next/next.config.js, apps/next/package.json, apps/next/pages/sign-in.tsx, packages/app/features/auth/sign-in-screen.tsx, packages/app/utils/getPlaiceholderImage.ts, yarn.lock
Use `plaiceholder` library to progressively oad remote images from github
Using SSR here, which is causing some funny loading state. I'll handle that in a future PR
The image are held in `0xsend/assets` repo. 
Styling of theses pages will be handled in future PRs
=> Progressive image loading with solito image

packages/app/components/sidebar/AuthSideBar.tsx, packages/app/features/auth/components/Carousel.tsx, packages/app/features/auth/components/VerifyCode.tsx, packages/app/features/auth/layout.web.tsx, packages/app/features/auth/onboarding/onboarding-form.tsx, packages/app/features/auth/onboarding/screen.tsx, packages/app/features/auth/sign-in/screen.tsx, packages/app/features/auth/sign-in/sign-in-form.tsx, packages/playwright/tests/fixtures/send-accounts/page.ts
Mirrors the implementation used in `sign-in-form.tsx`
=> Make Onboarding Form an actual form

apps/next/pages/_app.tsx, apps/next/pages/activity.tsx, apps/next/pages/checkout.tsx, apps/next/pages/leaderboard.tsx, apps/next/pages/referrals.tsx, apps/next/pages/send.tsx, packages/app/features/account/earn-tokens/components/DistributionClaimButton.tsx, packages/app/features/account/earn-tokens/screen.tsx
=> Replace titles with /send

.github/workflows/ci.yml, packages/app/features/auth/onboarding/index.test.ts, packages/app/features/auth/onboarding/onboarding-form.tsx, packages/app/utils/userop.ts, packages/wagmi/src/generated.ts, packages/wagmi/wagmi.config.ts
sometimes phone provider isn't working and needs to be disabled and re-enabled.
=> try to fix supabase branching update

packages/app/components/HomeTopNav.tsx
Centers the HomeTopNav components on mobile where we don't have to align with sidebar
=> Center TopNav component on mobile

packages/app/features/account/earn-tokens/screen.tsx
Make sure distributions are in right order and add little 🥕 on the selected distribution
=> Sort distributions by number & button caret

packages/app/__mocks__/wagmi.ts, packages/app/features/account/earn-tokens/__snapshots__/screen.test.tsx.snap, packages/app/features/account/earn-tokens/components/DistributionClaimButton.tsx, packages/app/features/account/earn-tokens/screen.test.tsx, packages/app/features/account/earn-tokens/screen.tsx, packages/app/utils/useTimeRemaining.ts, packages/shovel/test/__snapshots__/index.test.ts.snap
- claim button fixes
- test distribution
- clean up distribution numbers
=> app: distribution clean up

packages/app/components/sidebar/HomeSideBar.tsx, packages/app/features/account/components/editProfile/screen.tsx, packages/app/features/account/settings/SettingsNavLink.tsx, packages/app/features/account/settings/layout.web.tsx
fix weird tamagui bug where sizes weren't applied in prod correctly
add more UI elements
remove extra texts on edit profile
=> app: bug fixes and UI updates

packages/app/components/HomeTopNav.tsx, packages/app/features/account/AccountTopNav.tsx, packages/app/features/home/__snapshots__/screen.test.tsx.snap, packages/app/features/home/screen.tsx, packages/ui/src/components/Container.tsx
fixes ultrawide screen header position
makes spacing between header and screen consistent
=> ui: clean up container and spacings

apps/next/pages/activity.tsx, apps/next/pages/profile/[tag].tsx, apps/next/pages/secret-shop.tsx, packages/app/components/TopNav.tsx, packages/app/features/account/settings/personal-info.tsx, packages/app/features/auth/components/VerifyCode.tsx, packages/app/features/auth/sign-in/sign-in-form.tsx, packages/app/features/secret-shop/screen.tsx
add noSubroute option to TopNav
fix lint warnings
=> app: add TopNav to more screens

apps/next/pages/account/settings/support.tsx, packages/app/features/account/settings/support.tsx
=> add support link redirect on web

packages/app/features/account/sendtag/checkout/checkout-form.tsx, packages/ui/src/components/FormFields/TextField.tsx
Looks like some tests need to be fixed
=> Error Tooltip for TextFields

packages/app/components/TopNav.tsx, packages/app/features/auth/sign-in/sign-in-form.tsx, packages/ui/src/components/FormFields/CountryCodeField.tsx, packages/ui/tsconfig.json
Adjust styling and alignment of elements in the TopNav component
Add validation to the phone field in the SignInForm
Fix styling and add web-specific props to the CountryCodeField component
Include necessary app/utils files in the UI package build
=> app updates and ui fixes

apps/next/pages/account/settings/support.tsx, packages/app/components/sidebar/HomeSideBar.tsx, packages/app/components/sidebar/SideBarNavLink.tsx, packages/app/features/account/sendtag/checkout/checkout-form.tsx, packages/app/features/account/settings/SettingsBottomSheet.tsx, packages/app/features/account/settings/support.tsx
remove support redirect
fix sidebarnavlink scaling
fixes biome unused import warnings
=> app: support screen and settings links

packages/app/features/account/sendtag/checkout/SendTagPricingDialog.tsx, packages/app/features/account/sendtag/checkout/checkout-form.tsx
We really need to get this Radix color schema locked down. Color styles are getting pretty messy
=> SendTag Pricing Tooltip

packages/app/components/icons/IconInfoGreenCircle.tsx
=> Fix biome lint build error

CONTRIBUTING.md, Tiltfile
updates contributing docs with some more notes about using tilt.
fixes some next dependencies in the tiltfile.
=> contributing docs update

apps/next/pages/activity.tsx, apps/next/pages/auth/onboarding.tsx, apps/next/pages/leaderboard.tsx, apps/next/pages/profile/[tag].tsx, apps/next/pages/qr-scan.tsx, apps/next/pages/receive.tsx, apps/next/pages/referrals.tsx, apps/next/pages/send.tsx, apps/next/utils/userProtected.ts, packages/app/components/sidebar/HomeSideBar.tsx, packages/app/features/account/rewards/components/DistributionClaimButton.tsx, packages/app/features/account/rewards/screen.test.tsx, packages/app/features/home/TokenDetails.tsx, packages/app/features/home/screen.test.tsx, packages/app/jest.config.ts, packages/app/utils/useSendAccountBalances.ts, packages/contracts/foundry.toml
deploys on staging base sepolia 84532:
deploys on production base 8453:
=> migrate to base deploy

.snaplet/snaplet-client.d.ts, .snaplet/snaplet.d.ts, packages/app/features/account/__snapshots__/screen.test.tsx.snap, packages/app/features/account/screen.tsx, packages/app/features/send/screens/receive/receive-tag.tsx, packages/app/features/send/screens/send/send-tag.tsx, packages/snaplet/README.md, supabase/database-generated.types.ts, supabase/database.types.ts, supabase/migrations/20240329185908_add_profiles_send_id.sql, supabase/tests/profile_send_id_test.sql
Add SendID and backfill based on account created.
=> Adding SendID to account screen, backfilling existing send ids

packages/app/features/auth/onboarding/__snapshots__/screen.test.tsx.snap, packages/app/features/profile/__snapshots__/SendDialog.test.tsx.snap, packages/ui/src/components/SubmitButton.tsx
Uses the `<Unspaced/>` component to remove the Spacer that comes with  `<AnimatePresence/>
=> Fix Submit Button spacing

apps/next/pages/activity.tsx, apps/next/pages/auth/onboarding.tsx, apps/next/pages/leaderboard.tsx, apps/next/pages/profile/[tag].tsx, apps/next/pages/qr-scan.tsx, apps/next/pages/receive.tsx, apps/next/pages/referrals.tsx, apps/next/pages/send.tsx, apps/next/utils/userProtected.ts, packages/app/components/sidebar/HomeSideBar.tsx, packages/app/features/home/TokenDetails.tsx, packages/app/features/home/screen.test.tsx, packages/app/utils/useSendAccountBalances.ts
This reverts commit 0a861f68c0c3e6feaaa973e57cd34b9ab9493a14.
=> MVP is back on track. Revert "disable stuff"

.github/workflows/ci.yml, Tiltfile
run tilt down if tilt not skipped
=> try barg self-hosted

apps/next/pages/account/rewards.tsx, packages/app/features/account/rewards/__snapshots__/screen.test.tsx.snap, packages/app/features/account/rewards/screen.test.tsx, packages/app/features/account/rewards/screen.tsx, packages/app/features/account/sendtag/checkout/SendTagPricingDialog.tsx, packages/playwright/tests/account-rewards.onboarded.spec.ts
Small Typo fixes
Show value of rewards in USD
=> Cherrypick small changes made in dev to main to ship them faster

packages/app/features/account/rewards/__snapshots__/screen.test.tsx.snap, packages/app/features/account/rewards/components/DistributionClaimButton.tsx, packages/app/features/account/rewards/screen.tsx, packages/app/features/account/sendtag/checkout/checkout-form.tsx, packages/app/features/account/sendtag/checkout/components/checkout-confirm-button.tsx
handle requesting tx state in checkout
Fix rewards card padding & check if claimed first
=> cherrypick-changes-to-reward-padding

tsconfig.base.json
=> add noUncheckedIndexedAccess check

apps/distributor/src/__snapshots__/distributor.test.ts.snap, apps/distributor/src/app.ts, apps/distributor/src/distributor.test.ts, apps/distributor/src/distributor.ts, apps/distributor/src/supabase.ts, apps/distributor/src/wagmi.ts
Fix includes fixed pool amount in the total share amount calculation.
Add test for calculating distribution shares.
Refactor distributor:
- Extract database queries to separate functions in supabase.ts:
- fetchDistribution for fetching distribution data
- fetchAllVerifications for fetching user verifications
- fetchAllHodlers for fetching hodler addresses
- createDistributionShares for creating distribution shares
- Extract balance fetching logic to fetchAllBalances in wagmi.ts
- Move supabaseAdmin to supabase.ts for better organization
Update distributor tests:
- Add test for calculating distribution shares
- Mock external dependencies in tests
Update distributor snapshot:
- Add snapshot for distribution 4 merkle root
Other changes:
- Add constructor parameter to DistributorWorker to …
=> distributor: fix share amount calculation and refactor code

packages/app/components/TopNav.tsx, packages/app/data/coins.tsx, packages/app/features/home/TokenBalanceCard.tsx, packages/app/features/home/TokenBalanceList.tsx, packages/app/features/home/__snapshots__/screen.test.tsx.snap, packages/app/features/home/screen.tsx
Move Files around and rename to get ready to implement token details screens and components
=> Prepare Home Screen for TokenDetails page

packages/app/components/TopNav.tsx, packages/app/data/coins.tsx, packages/app/features/home/TokenBalanceCard.tsx, packages/app/features/home/TokenBalanceList.tsx, packages/app/features/home/__snapshots__/screen.test.tsx.snap, packages/app/features/home/screen.test.tsx, packages/app/features/home/screen.tsx, packages/app/routers/params.tsx
WIP token details page
Ethen wanted to show this to users. Should be clean enough for now.
Running into a lot of problems because `TopNav` doesn't ergonomically support switching the nav with query params 
Future PRs will address the shortcomings with TopNav and further flesh out the feature set of this page
=> Basic Token Details Page

.gitignore, CONTRIBUTING.md
This PR updates the `.gitignore` file to exclude the `bun.lockb` file and fixes some styling in the contributing guide (`CONTRIBUTING.md`) as well as adding some info on potential issues that may be faced with `yarn`.
=> chore: onboarding - update CONTRIBUTING.md

packages/app/features/account/rewards/__snapshots__/screen.test.tsx.snap, packages/app/features/account/rewards/screen.test.tsx, packages/app/features/account/rewards/screen.tsx, packages/app/jest.config.ts, packages/app/jest.setup-after-env.ts, packages/app/jest.setup.ts, packages/app/tsconfig.json, packages/app/utils/useTimeRemaining.ts
makes rewards screen easier to test without relying on global mocks.
=> app: fix reward test

packages/app/features/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/activity/screen.test.tsx, packages/app/features/activity/screen.tsx, packages/ui/src/themes/colors.ts
Styles the search results pop up.
=> Style search results

packages/app/features/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/activity/screen.tsx
=> Add filter buttons to search

packages/app/features/send/components/SendSearch.tsx, packages/app/features/send/screen.tsx
Looks like the send search component got left out of the last PR
=> Fix: Send Search Component

packages/app/features/account/settings/backup/index.tsx
Styled the top section of the backup screen on dark mode
=> top text styles

packages/app/features/account/settings/backup/index.tsx
There aren't light theme designs in Figma yet, so I just added a few basics to get it all legible
=> light theme colors

packages/app/features/account/settings/backup/index.tsx
update the passkey credential card bg color
=> fix card color

apps/next/pages/account/rewards.tsx, apps/next/styles/globals.css, packages/app/components/TopNav.tsx, packages/app/features/home/TokenDetails.tsx, packages/app/features/home/layout.web.tsx, packages/app/features/home/screen.tsx, packages/app/utils/usePwa.ts
This might fix. Its hard to test since I can't get login working on my mobile device. It works in iOS simulator
Edit:
SUCCESSS
=> Maybe Fix: PWA top padding

packages/app/features/home/TokenBalanceCard.tsx, packages/app/features/home/TokenBalanceList.tsx, packages/app/features/home/TokenDetails.tsx, packages/app/features/home/__snapshots__/screen.test.tsx.snap, packages/app/utils/formatAmount.test.ts, packages/app/utils/formatAmount.ts
@0xBigBoss not happy with the approach here, but this would save us from having to write custom logic for decimal and integer per token
Care to give some input. Commented a test out that would no longer be relevant.
=> Format Integers and decimals of balances on home screen

.github/workflows/ci.yml, Brewfile, packages/app/utils/zod/activity/index.ts, packages/playwright/playwright.config.ts, packages/playwright/tests/activity.onboarded.spec.ts-snapshots/activity-feed-url-chromium.txt, packages/playwright/tests/activity.onboarded.spec.ts-snapshots/activity-feed-url-firefox.txt
Make Visual Tests More Forgiving
fix build warning/error
add sqlffluff to brew bundle
fix snapshots to match .env.local.template
add playwright test results in CI
=> add playwright test results in CI

.snaplet/snaplet.d.ts, packages/app/features/deposit/DepositPopover.tsx, packages/app/features/deposit/__snapshots__/screen.test.tsx.snap, packages/app/features/deposit/screen.test.tsx, packages/app/features/deposit/screen.tsx, packages/app/features/home/__snapshots__/screen.test.tsx.snap, packages/app/features/home/screen.tsx
- **update snaplet**
- **app: deposit screen and popover**
=> app: Deposit screen and Popover

apps/next/package.json, apps/next/pages/[tag].tsx, apps/next/utils/logRequest.ts, apps/next/utils/userProtected.ts, packages/app/components/FormFields/TextField.tsx, packages/app/features/account/components/editProfile/screen.tsx, packages/app/features/account/sendtag/checkout/checkout-form.tsx, packages/app/features/account/sendtag/checkout/checkout-utils.tsx, packages/app/features/account/sendtag/checkout/components/checkout-confirm-button.tsx, packages/app/features/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/auth/components/VerifyCode.tsx, packages/app/features/auth/onboarding/__snapshots__/screen.test.tsx.snap, packages/app/features/deposit/web3/__snapshots__/screen.test.tsx.snap, packages/app/features/deposit/web3/screen.tsx, packages/app/features/profile/__snapshots__/screen.test.tsx.snap, packages/app/features/profile/screen.tsx, packages/app/utils/useReceipts.ts, packages/contracts/script/anvil-add-send-merkle-drop-fixtures.ts, packages/playwright/tests/account-sendtag-checkout.logged-in.spec.ts, packages/playwright/tests/fixtures/profiles/test.ts, packages/playwright/tests/profile.onboarded.spec.ts, packages/wagmi/src/config.ts, supabase/database.types.ts, supabase/migrations/20240609180306_profile_constraints.sql, yarn.lock
- **app: fix deposit web3 screen**
- **app: better error messages**
- **fixup profile page**
- **add profile name and about constraints**
- **checkout fixes**
=> app: fixes and polish

supabase/migrations/20240614155029_fix_tag_search_confirmed_tags.sql, supabase/tests/tags_search_test.sql
Adds more tests for tag search
=> Fixes tag search to filter out unconfirmed tags

.vscode/extensions.json, Tiltfile
add color highlight extension recommendation
=> tilt fix ui dep

packages/app/utils/useUserOpTransferMutation.ts, packages/contracts/script/UpdateTokenPaymasterConfig.s.sol
in case of needing to update cached price, the post op
uses around 95K gas.
=> increase default paymaster post op gas limit

packages/app/features/send/confirm/screen.tsx, packages/app/utils/useUserOpTransferMutation.ts, packages/contracts/script/UpdateTokenPaymasterConfig.s.sol, tilt/infra.tiltfile
in case of needing to update cached price, the post op uses around 95K gas.
=> increase default paymaster post op gas limit (#506)

packages/app/features/profile/__snapshots__/screen.test.tsx.snap, packages/app/features/profile/screen.test.tsx, packages/app/features/profile/screen.tsx, packages/app/features/profile/utils/useInterUserActivityFeed.ts, packages/playwright/tests/fixtures/profiles/test.ts, packages/playwright/tests/profile.anon.spec.ts, packages/playwright/tests/profile.onboarded.spec.ts
=> profile styles

packages/app/features/profile/utils/useInterUserActivityFeed.ts
Only show transfer/receive in profile
=> filter events profile

packages/app/features/auth/sign-in/sign-in-form.tsx
fix this ticket
https://3.basecamp.com/5743564/buckets/36023883/todos/7589837995
=> passkey fail message

packages/app/features/send/confirm/screen.tsx, packages/app/utils/useUserOpTransferMutation.ts
fix for: 
https://3.basecamp.com/5743564/buckets/36023883/todos/7555101870
=> invalid passkey  message

.github/workflows/ci.yml, packages/api/src/routers/tag.ts, packages/api/tsconfig.json, packages/app/components/SearchBar.tsx, packages/app/features/account/sendtag/checkout/SendTagPricingDialog.tsx, packages/app/features/account/sendtag/checkout/checkout-form.tsx, packages/app/features/account/sendtag/checkout/checkout-utils.tsx, packages/app/features/account/sendtag/checkout/components/checkout-confirm-button.tsx, packages/app/features/auth/onboarding/__snapshots__/screen.test.tsx.snap, packages/app/features/auth/onboarding/index.test.ts, packages/app/features/home/TokenDetailsHistory.tsx, packages/app/features/secret-shop/screen.tsx, packages/app/features/send/SendAmountForm.tsx, packages/app/features/send/confirm/screen.tsx, packages/app/features/send/screen.test.tsx, packages/app/utils/useSetErc20Balance.ts, packages/app/utils/userop.ts, packages/playwright/tests/fixtures/viem/base.ts, packages/playwright/tests/send.onboarded.spec.ts, tilt/apps.Tiltfile, tilt/infra.Tiltfile, tilt/tests.Tiltfile
Updates namings to prepare for accepting USDC for Sendtags.
=> Sendtag pricing update preparations

.env.local.template, packages/app/tsconfig.json, packages/app/utils/useProfileLookup.ts, packages/app/utils/userop.ts, packages/playwright/playwright.config.ts, packages/playwright/tests/fixtures/send-accounts/page.ts, packages/playwright/tests/sign-in.anon.spec.ts, packages/playwright/tsconfig.json, supabase/database.types.ts
* fix sign in spec
* clean up useProfileLookup and tsconfigs
* add playwright record option
* only wait 10 seconds for send account create request
* app: estimate call gas limit
=> prep and clean up for sendtag checkout

packages/shovel/etc/config.json, packages/shovel/src/integrations/send-account-transfers.ts, packages/shovel/test/__snapshots__/index.test.ts.snap
use filter ref again for send account transfers
=> shovel: update send_account_transfers

apps/next/pages/_app.tsx, packages/app/features/deposit/web3/__snapshots__/screen.test.tsx.snap, packages/app/features/deposit/web3/screen.test.tsx, packages/app/features/deposit/web3/screen.tsx, packages/playwright/tests/deposit.onboarded.spec.ts
add a little wallet button that pops the connect modal
=> open modal button

apps/next/utils/userProtected.ts
Redirect user to /auth/sign-in on invalid JWT. Catches previously uncaught exception.
=> Redirect user on invalid JWT for re-auth

packages/app/features/deposit/web3/screen.test.tsx, packages/app/features/deposit/web3/screen.tsx, packages/app/features/home/screen.test.tsx, packages/app/features/home/screen.tsx, packages/app/features/send/__snapshots__/screen.test.tsx.snap, packages/app/features/send/confirm/screen.tsx, packages/app/features/send/screen.test.tsx, packages/app/utils/useSendAccountBalances.ts
* Standardize useSendAccountBalances hook
* Fix Send Button and Fees on confirm screen
* Change min USDC to 0.25
* Add Spinner if Balancesare loading in home
* Change in USDC to 0.20 (#671)
* always return isLoading fron useSendAccountBalances
* Fix Send Unit test
* Show balances when under min USDC
---------
=> Merge QA -> Dev (#675)

packages/app/features/home/__snapshots__/screen.test.tsx.snap, packages/app/features/home/screen.tsx, packages/playwright/tests/send.onboarded.spec.ts
Fixes failing `send.onboarded` tests
=> send onboarded test

packages/app/features/auth/components/SignInButton.tsx, packages/app/features/auth/sign-in/sign-in-form.tsx, packages/app/features/splash/screen.tsx, packages/playwright/tests/sign-in.anon.spec.ts, packages/playwright/tests/sign-up.anon.spec.ts
* Updated home screen design
* Opens passkeys directly without having to navigate to the sign in page
=> splash page designs

apps/next/pages/account/rewards.tsx, docs/testing-send-merkle-drop.md, packages/app/components/TopNav.tsx, packages/app/features/account/sendtag/checkout/checkout-form.tsx, packages/app/features/account/settings/SettingsLinks.tsx, packages/playwright/tests/account-rewards.onboarded.spec.ts
Knocks out a few smol changes that were requested:
* Decrease this space below the Send logo and menu. Cut it in half
* remove notifications, security, privacy from settings
* Fix alignment on subtext rewards page
=> minor updates

packages/app/features/account/settings/SettingsLinks.tsx, packages/app/features/account/settings/SettingsNavLink.tsx, packages/app/features/account/settings/layout.web.tsx
Adds card for settings, minor link style updates. each individual settings section will be stacked
=> settings section

packages/app/features/account/rewards/activity/screen.tsx, supabase/database-generated.types.ts, supabase/migrations/20241028085405_update_app_activity_metrics_view_to_use_weight_column.sql
Update app activity metrics view
- Create types for multiplier info and verification info
- Use new weight column
Update activity rewards screens
=> Update app activity metrics view

packages/app/features/account/rewards/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/account/rewards/activity/screen.tsx
- Hide empty active multipliers
- Always show weights for send streak and tags registered
=> Cleanup activity screen

packages/api/src/routers/auth/router.ts, packages/app/features/auth/sign-up/sign-up-form.tsx
disabled backing up page, not removing all the code, because I might need it to build another solution
=> Disabled backing up page

packages/app/features/account/rewards/activity/screen.tsx
=> Use || for previousReward falsy value

apps/next/styles/globals.css, packages/app/features/profile/screen.tsx
=> Added profile info to transaction history

packages/app/components/NavSheet.tsx, packages/app/components/ReferralLink.tsx, packages/app/components/sidebar/HomeSideBar.tsx, packages/app/components/sidebar/SideBarNavLink.tsx
=> Redesigned mobile nav

packages/app/features/home/TokenActivityRow.tsx, packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap
=> Activity row gap tweak

packages/app/components/ReferralLink.tsx, packages/app/components/sidebar/HomeSideBar.tsx
=> Handled too long referrals on mobile

packages/app/features/activity/RecentActivity.tsx, packages/app/features/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/activity/screen.tsx, packages/app/features/home/TokenActivityRow.tsx, packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap, packages/app/provider/tag-search/TagSearchProvider.tsx, packages/playwright/tests/activity.onboarded.spec.ts
=> Redesign activity

apps/next/pages/activity.tsx, packages/app/components/SearchBar.tsx, packages/app/components/TopNav.tsx, packages/app/features/activity/RecentActivity.tsx, packages/app/features/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/activity/screen.tsx, packages/app/features/home/TokenActivityRow.tsx, packages/app/features/home/TokenDetailsHistory.tsx, packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap
- added header on desktop
- aligned fonts and spacings with figma
- aligned search size with content size
=> UI adjustments on activity

packages/app/features/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/home/TokenDetails.test.tsx, packages/app/features/home/TokenDetails.tsx, packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap, packages/app/provider/coins/CoinsProvider.tsx, packages/app/utils/useSendAccountBalances.ts, packages/app/utils/useTokenPrices.ts
This fixes our prices immediately
In the future we can use coingecko and fallback to dexscreener if coingecko rate limits us
=> Use dexscreener for prices

packages/contracts/script/gen-dist-merkle-tree.ts
Fixed numeric precision handling in distribution merkle tree generation script
- Modified the SQL query to return amount as text instead of numeric
- Updated the total calculation to use BigInt operations to prevent precision loss
- Extracted distribution shares query into a separate function for better code organization
- Added type safety with SupabaseClient typing
1. Run the merkle tree generation script with a distribution ID
2. Verify that large numbers are handled correctly without precision loss
3. Confirm that the generated merkle tree contains accurate amount values
JavaScript has limited precision when handling large numbers. By treating amounts as strings and using BigInt for calculations, we ensure accurate handling of large token amounts in the distribution system without any …
=> Update MerkleTree Gen to use bigint

packages/app/utils/distributions.ts
Fixed decimal precision calculation in distribution multiplier formula by rounding to one decimal place, improving accuracy in distribution outcomes.
- Fixed rounding errors in multipliers
- Updated multiplier calculation for consistent decimal precision
- Improved accuracy in distribution outcomes
=> Handle rounding errors in multipliers

packages/ui/src/utils/useSafeAreaInsets.ts
The PR introduces a new approach to handling safe area insets, utilizing a cache and a module state to improve performance. It reduces unnecessary updates and sanitizes safe area inset values.
- Introduces a cache for safe area insets
- Uses a module state to track initialization
- Improves performance by reducing unnecessary updates
- Sanitizes safe area inset values
=> try module state and cache for safearea

packages/app/components/MobileButtonRowLayout.tsx, packages/app/components/NavSheet.tsx, packages/app/components/TopNav.tsx, packages/app/features/auth/layout.web.tsx, packages/app/features/home/layout.web.tsx, packages/app/features/send/components/SendTopNav.tsx, packages/app/features/send/confirm/screen.tsx, packages/app/utils/activity.ts, packages/ui/src/components/Container.tsx
I made a 24 min video on how I used graphite to make this stack
Let me know if you are interested in watching it and I'll post it somewhere
=> Refactor Container to use SafeArea

apps/next/pages/deposit/success.tsx, apps/next/pages/deposit/success/callback.tsx, apps/next/pages/deposit/success/index.tsx, packages/app/features/deposit/coinbase/screen.tsx, packages/app/features/deposit/components/SuccessCallback.tsx, packages/app/features/deposit/components/SuccessScreen.tsx, packages/app/utils/useCoinbaseOnramp.ts
Coinbase Onramp popup is not in sync with the app which leads to infinite loading spinning.
=> fix(app): sync coinbase popup

packages/app/features/deposit/screen.tsx
=> fix(app): remove onramp user allowlist check

packages/app/features/account/sendtag/add/AddSendtagsForm.tsx, packages/app/features/account/sendtag/checkout/checkout-form.tsx, packages/app/features/account/sendtag/checkout/screen.tsx, packages/app/features/account/sendtag/screen.tsx
The PR introduces several UI changes and improvements to the Sendtag feature, including the repositioning of tags buttons, addition of a paragraph explaining Sendtag security, and modifications to the checkout form and screen layouts.
- Repositioned tags buttons for better user experience
- Added a paragraph explaining Sendtag security
- Modified checkout form layout
- Updated Sendtag screen layout
=> Tags buttons position unification

apps/next/pages/[tag].tsx, packages/app/features/account/sendtag/add/AddSendtagsForm.tsx, packages/app/features/account/sendtag/checkout/screen.test.tsx, packages/app/utils/zod/sendtag.ts
=> Extract Sendtag Zod Type

packages/api/src/routers/tag.ts, packages/app/features/account/sendtag/checkout/checkout-form.tsx, packages/app/features/account/sendtag/checkout/checkout-utils.ts, packages/app/features/account/sendtag/checkout/components/checkout-confirm-button.tsx, packages/app/utils/useReferralCodeCookie.ts, packages/app/utils/useReferrer.ts
TODO: we should convert checkout page back to a form
=> Use new referrer_lookup function in checkout

packages/app/components/FormFields/CoinField.tsx, packages/app/features/home/TokenBalanceList.tsx, packages/app/features/home/screen.tsx, packages/app/features/swap/form/__snapshots__/screen.test.tsx.snap, packages/app/features/swap/form/screen.tsx, packages/app/utils/userop.ts
This PR introduces several UI/UX improvements and bug fixes to the swap form and token balance list. 
Changes include making the token select field scrollable, fixing the enter button, and improving the preVerificationGas logic.
- Made token select field scrollable on non-touchable devices
- Fixed enter button issue on swap form
- Improved preVerificationGas logic to dodge potential errors
- Fixed token label glitching on smaller devices
- Added cursor pointer on coin field
=> Some swap UI/UX polishes

packages/api/src/routers/swap/types.ts
Adjusted API to accommodate Kyberswap changes, making certain fields optional.
- Made limitReturnAmount optional
- Made poolLength optional
=> Adjust to kyberswap API changes

packages/app/features/send/screen.test.tsx
This PR adds more unit tests for the SendScreen component, including tests for rendering search when no profile is returned from profile lookup and rendering no send account when the returned profile has no address.
- Added test for rendering search when no profile is returned
- Added test for rendering no send account when profile has no address
- Mocked useProfileLookup to test different scenarios
- Updated jest mocks for useTagSearch and SearchBar components
=> More unit tests for send screen

packages/app/features/deposit/crypto/screen.tsx
Improved the layout and design of the wallet address section in the crypto deposit screen on mobile.
- Improved wallet address layout
- Enhanced button design
- Added flexShrink to IconCopy
=> Improved wallet address in crypto deposit on mobile

packages/app/utils/coin-gecko/index.tsx
Added a new hook to fetch market data for multiple tokens at once, utilizing the CoinGecko API.
- Added `useMultipleTokensMarketData` hook
- Supports fetching market data for multiple tokens
- Utilizes CoinGecko API
- Added type definition for `MarketData`
=> Add hook to fetch multiple tokens market data

packages/app/features/auth/components/VerifyCode.tsx, packages/app/features/auth/onboarding/__snapshots__/screen.test.tsx.snap, packages/app/features/auth/onboarding/onboarding-form.tsx, packages/app/features/auth/sign-up/sign-up-form.tsx, packages/app/features/home/HomeQuickActions.tsx, packages/app/features/home/TokenBalanceCard.tsx, packages/app/features/home/TokenBalanceList.tsx, packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap, packages/app/features/home/screen.tsx, packages/ui/src/components/BigHeading.tsx
The PR introduces several enhancements to the home page and authentication components. 
It updates the `VerifyCode` component, modifies the `BigHeading` component, 
and enhances the `TokenBalanceList` and `TokenBalanceCard` components.
- Updates `VerifyCode` component props
- Modifies `BigHeading` component to include fontWeight
- Enhances `TokenBalanceList` and `TokenBalanceCard` components
- Updates home page layout and styling
=> Add more data in token rows on home page

apps/next/pages/earn/index.tsx, packages/app/components/ComingSoon.tsx, packages/app/components/TopNav.tsx
Added a new stub page for the earn feature, including a coming soon message and top navigation.
- Added earn page with coming soon message
- Updated TopNav to include earn route
- Created new ComingSoon component
=> Add stub page for earn

apps/next/pages/sendpot/index.tsx, packages/app/components/TopNav.tsx
Added a coming soon page for Sendpot, including a new page component and updates to the TopNav component.
- Added Sendpot coming soon page
- Updated TopNav component to include Sendpot
- Created new page component for Sendpot
=> Add coming soon page for sendpot

apps/next/pages/feed/index.tsx, packages/app/components/TopNav.tsx
Added a coming soon page for the feed feature, including a new page component and updates to the TopNav component.
- Added coming soon page for feed
- Updated TopNav component to include feed route
=> Add coming soon page for feed

apps/next/pages/invest/index.tsx, packages/app/components/TopNav.tsx, packages/app/features/invest/screen.tsx, packages/ui/src/components/LinkBanner.tsx
Added a new invest page with a link banner and server-side rendering.
- Added invest page
- Updated TopNav component
- Created InvestScreen component
- Updated LinkBanner component
=> Added invest page

packages/app/components/BottomTabBar/BottomNavBar.tsx, packages/app/components/sidebar/HomeSideBar.tsx
Updated the BottomNavBar and HomeSideBar components to add new pages and improve styling.
- Added new pages to the sidebar
- Updated BottomNavBar styling
- Added Explore and Invest pages
=> Added new pages to side bar

packages/app/features/sendpot/BuyTicketsScreen.tsx, packages/app/features/sendpot/DrawingHistory.tsx
The PR introduces several UI updates to the BuyTicketsScreen and DrawingHistory components. 
The updates include changes to layout, styling, and the addition of new text elements.
- Updated BuyTicketsScreen layout
- Added flexWrap to XStack components
- Introduced new text elements for ticket price and total cost
- Modified DrawingHistory component layout
=> Megapot misc ux updates

packages/app/features/sendpot/BuyTicketsScreen.tsx, packages/app/features/sendpot/DrawingHistory.tsx
=> update misc megapot ux (#1287)

packages/app/features/home/TokenBalanceCard.tsx
The PR introduces minor layout adjustments and styling changes to the TokenBalanceCard component.
- Updated Card component props
- Added fontSize to BigHeading component
=> Total balance polishes

apps/next/pages/explore/index.tsx, apps/next/pages/invest/index.tsx
Made invest and explore pages public by removing user protection.
- Removed user protection from invest page
- Removed user protection from explore page
=> Made invest and explore pages public

packages/app/features/account/__snapshots__/screen.test.tsx.snap, packages/app/features/account/screen.tsx
Fixed UI glitch on account page for desktop devices by adjusting layout properties.
- Fixed UI glitch on account page
- Updated layout for desktop devices
=> Fixed odd UI glitch on account page on desktop

packages/app/components/TopNav.tsx
The PR updates the TopNav component to make the avatar clickable and redirect to the account page.
- Updated TopNav component to use LinkableAvatar
- Changed avatar click behavior to redirect to account page
- Removed handleHomeBottomSheet function
- Updated avatar styling and layout
=> Made top nav avatar click go to account page

apps/next/pages/activity.tsx, packages/app/features/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/activity/screen.test.tsx, packages/app/features/activity/screen.tsx
The PR removes the 'My' prefix from the activity page header and search functionality.
It also simplifies the `ActivityScreen` component by removing the `TagSearchProvider` and `Search` components.
- Removed 'My' prefix from activity page header
- Removed search functionality from activity page
- Simplified `ActivityScreen` component
=> Removed word 'My' and search from activity page

packages/app/features/earn/deposit/screen.tsx, packages/app/features/earn/hooks/index.ts, packages/app/features/earn/withdraw/screen.tsx, packages/app/utils/send-accounts/useSendAccounts.ts, packages/app/utils/useAddressBook.ts, packages/app/utils/useSwapRouters.ts
* fix: update form validation to check for errors instead of validity in WithdrawForm
* fix: smaller stale times
* fix: invalidate send_earn_balances
=> fix: send earn tweaks

packages/app/features/earn/earnings/screen.tsx
=> fix(app): update earnings screen

packages/app/features/earn/earnings/screen.tsx
=> fix(app): update earnings screen (#1307)

packages/app/components/BottomTabBar/BottomNavBar.tsx, packages/app/features/account/screen.tsx
Updated the BottomNavBar component to display on larger screens and made layout adjustments for better responsiveness.
- Updated BottomNavBar display condition
- Added center alignment to LinearGradient
- Adjusted XStack layout for larger screens
- Updated AccountScreen layout for better responsiveness
=> Added bottom nav bar for tablets

apps/next/pages/explore/index.tsx, apps/next/pages/invest/index.tsx, packages/app/components/TopNav.tsx, packages/app/features/send/components/SendTopNav.tsx
The PR introduces changes to the main pages' headers, including the removal of the back button and adjustments to the text size.
- Updated main pages' headers to have larger text
- Removed back button from main pages' headers
- Added conditional rendering of back button in TopNav component
- Changed header text in SendTopNav component
=> Aligned main pages headers to have larger text and no back button

packages/app/features/activity/RecentActivity.tsx, packages/app/features/activity/__snapshots__/screen.test.tsx.snap, packages/app/features/activity/screen.test.tsx
The PR introduces several enhancements to the RecentActivity component, including the addition of scroll direction detection, automatic fetching of the next page when the user reaches the end of the list on small screens, and improvements to the layout and rendering of the activity feed.
- Added scroll direction detection
- Implemented automatic fetching of the next page on small screens
- Improved layout and rendering of the activity feed
- Added ScrollDirectionProvider to the ActivityScreen component
=> Put activity screen behind bottom nav bar

packages/app/features/account/__snapshots__/screen.test.tsx.snap, packages/app/features/account/screen.tsx
The AccountScreen component has been updated to improve its layout and responsiveness.
- Updated YStack component with aspectRatio
- Changed height to aspectRatio for better responsiveness
=> Put account page behind bottom nav bar

packages/app/features/send/components/SendTopNav.tsx
Added account avatar on main send page for mobile users, enhancing the user interface.
- Added AvatarMenuButton component
- Imported useUser hook
- Displayed user profile avatar on send page
=> Added account avatar on main send page on mobile

packages/app/features/account/sendtag/add/AddSendtagsScreen.tsx, packages/app/features/account/sendtag/checkout/screen.tsx, packages/app/features/account/sendtag/screen.tsx, packages/app/features/deposit/__snapshots__/screen.test.tsx.snap, packages/app/features/deposit/screen.tsx, packages/app/features/earn/active/screen.tsx, packages/app/features/earn/withdraw/screen.tsx, packages/app/features/profile/__snapshots__/screen.test.tsx.snap, packages/app/features/profile/screen.tsx, packages/app/features/send/SendAmountForm.tsx, packages/app/features/send/__snapshots__/screen.test.tsx.snap, packages/app/features/send/confirm/screen.tsx, packages/app/features/swap/form/__snapshots__/screen.test.tsx.snap, packages/app/features/swap/form/screen.tsx, packages/app/features/swap/summary/__snapshots__/screen.test.tsx.snap, packages/app/features/swap/summary/screen.tsx
Removed unnecessary spacing above bottom nav bar and adjusted padding in various screens.
- Removed unnecessary spacing above bottom nav bar
- Adjusted padding in SendTag screens
- Updated padding in Deposit screen
- Changed padding in Earn and Withdraw screens
- Modified padding in Profile and SendAmountForm screens
- Updated padding in SendConfirm and SwapForm screens
=> Removed unnecessary spacing above bottom nav bar

packages/app/features/swap/summary/__snapshots__/screen.test.tsx.snap, packages/app/features/swap/summary/screen.tsx
Increased the clickable area of the edit button on the trade page.
- Increased edit button clickable area
- Improved accessibility
=> Made edit button on trade page more accessible

packages/app/routers/params.tsx
Changed the default send token to 'send' if the user has a balance, and updated import statements.
- Updated import statements for coins and viem.
- Changed default send token based on user balance.
- Added useCoin hook for SEND coin.
=> Changed default send token to send if user has balance

packages/app/components/sidebar/HomeSideBar.tsx
The PR introduces several changes to the HomeSideBar component, including the addition of a new link to the 'Activity' page and the introduction of a new DesktopAccountMenuEntry component.
- Added link to 'Activity' page
- Removed 'Trade' link
- Introduced DesktopAccountMenuEntry component
- Updated HomeSideBar component styling
=> Cleaned up side menu on desktop

packages/app/components/sidebar/HomeSideBar.tsx
Improved user experience in the account menu entry on desktop by adding loading state handling.
- Added loading state handling for profile and tags
- Introduced opacity animation for loading state
- Set fixed height for account menu entry
=> Better UX in account menu entry on desktop

packages/app/components/sidebar/HomeSideBar.tsx
Updated the DesktopAccountMenuEntry component to fix the background issue on desktop and improved hover styles.
- Fixed account menu entry background issue
- Updated hover and focus styles
=> Fixed account menu entry background issue on desktop

packages/app/features/home/TokenActivityRow.tsx, packages/app/features/profile/screen.tsx, packages/app/utils/activity.ts
The PR enhances the activity page by showing notes and improving the user experience.
- Added notes to activity page
- Improved user transfer handling
- Enhanced profile screen with activity details
=> Show notes in activity page

packages/app/components/BottomTabBar/BottomNavBar.tsx, packages/app/components/FormFields/CoinField.tsx, packages/app/components/sidebar/HomeSideBar.tsx, packages/app/components/sidebar/SideBarNavLink.tsx, packages/app/features/swap/form/screen.tsx, packages/app/utils/useHoverStyles.ts
The PR introduces several UI changes and enhancements to the menu on desktop, including updates to the BottomNavBar, CoinField, HomeSideBar, SideBarNavLink, and Slippage components. The changes aim to improve the overall user experience and consistency of the UI.
- Updated BottomNavBar with new hover styles
- Changed CoinField to use backgroundColor instead of background
- Refactored HomeSideBar with new layout and styling
- Enhanced SideBarNavLink with new icon rendering and hover styles
- Updated Slippage component with new backgroundColor
=> UI changes in menu on desktop

packages/app/features/profile/screen.tsx
Fixed the positioning of the history avatar in the profile screen.
- Fixed history avatar position
- Added alignSelf styling to XStack component
=> Fixed history avatar position

packages/app/features/home/TokenBalanceCard.tsx, packages/app/features/home/TokenBalanceList.tsx, packages/app/features/home/screen.tsx, packages/app/features/home/utils/useIsPriceHidden.tsx
The PR introduces a new feature to hide prices in the TokenBalanceCard and TokenBalanceList components. It also adds a provider to manage the isPriceHidden state and a hook to access this state.
- Added IsPriceHiddenProvider to manage isPriceHidden state
- Introduced useIsPriceHidden hook to access isPriceHidden state
- Modified TokenBalanceCard to hide prices when isPriceHidden is true
- Modified TokenBalanceList to hide prices when isPriceHidden is true
- Added slashes to display when prices are hidden
=> Added slashes on all assets

packages/app/features/profile/screen.tsx
Added functionality to allow users to send to themselves from transactions history.
- Added SendButton for self-send functionality
- Removed conditional rendering of SendButton
=> Allowed users send to themselves from transactions history

packages/app/features/activity/ActivityDetails.tsx, packages/app/features/home/TokenActivityRow.tsx, packages/app/features/profile/screen.tsx, packages/app/utils/activity.tsx
Added spinners to indicate pending temporal transfers and refactored date handling for activities.
- Added spinners for pending temporal transfers
- Refactored date handling for activities
- Improved date display for temporal transfers
=> Added spinners when temporal transfer is pending

packages/app/components/sidebar/HomeSideBar.tsx
Reordered menu items on the desktop sidebar.
- Reordered menu items
- Moved Activity below Send
=> Reorder menu items on desktop

packages/app/features/explore/rewards/activity/screen.tsx
Removed the rewards header from the ActivityRewardsScreen component.
- Removed Header component
- Removed imports for unused components
- Updated ActivityRewardsScreen to remove Header
=> Removed rewards header

packages/app/features/activity/ActivityAvatar.tsx, packages/app/utils/activity.tsx
Removed transfer direction indicator and updated event names for activities.
- Removed transfer direction indicator component
- Updated event names for transfer and receive activities
- Simplified event name logic
=> Removed transfer direction indicator

apps/next/next.config.js
Removed viem from optimizePackageImports to fix local build issues.
- Removed viem from optimizePackageImports
=> Removed viem from optimizePackageImports

packages/app/components/ReferralLink.tsx, packages/app/features/affiliate/screen.tsx
The PR updates the ReferralLink component and FriendsScreen to improve the user experience.
- Removed label prop from ReferralLink component
- Updated ReferralLink component to always display "Referral Code:"
- Changed ButtonText background color to transparent
- Updated FriendsScreen to display a paragraph and ReferralLink when no referrals exist
=> Fixed no friends message

packages/api/src/routers/tag/router.ts
Fixed tag availability check by updating the database query to correctly handle confirmed and pending tags.
- Updated tag availability check logic
- Improved error handling for database queries
- Added time-based filtering for pending tags
=> Fixed tag availability check

packages/api/src/routers/tag/router.ts, packages/snaplet/.snaplet/dataModel.json, packages/snaplet/.snaplet/snaplet-client.d.ts, packages/snaplet/.snaplet/snaplet.d.ts, supabase/database-generated.types.ts, supabase/migrations/20250520225147_fix_duplicated_foreign_key.sql
Removed duplicated foreign key and added computed relationship between profiles and tags.
- Removed duplicated foreign key constraint
- Added computed relationship between profiles and tags
- Updated database schema to reflect changes
=> Fixed duplicated foreign key

packages/app/features/swap/summary/screen.tsx, packages/app/utils/userop.ts
The PR improves the user experience on the trade summary screen by updating the spinner color and enhancing error handling for RPC requests.
- Updated spinner color to $color12
- Improved error handling for RPC requests
- Added check for 'return amount is not enough' error
=> Improved UX on trade summary

packages/app/features/auth/sign-up/screen.tsx, packages/app/utils/tags/useValidateSendtag.ts
The PR introduces several improvements to the sign-up process, including the addition of a new form state management system, enhancements to the validation and mutation of sendtags, and modifications to the sign-in and sign-up buttons.
- Improved form state management
- Enhanced sendtag validation and mutation
- Modified sign-in and sign-up buttons
- Updated error handling and messaging
=> Fixed sign up issues

packages/app/features/activity/utils/useRecentSenders.ts, packages/app/features/send/screen.tsx, supabase/database-generated.types.ts, supabase/migrations/20250523225148_recent_senders.sql
This PR introduces a new feature to display recent senders in the send screen, 
allowing users to quickly access their recent interactions.
- Added a new hook `useRecentSenders` to fetch recent senders data
- Implemented a `RecentSenders` component to display the recent senders
- Modified the `SendScreen` component to include the `RecentSenders` component
- Added a new SQL function `recent_senders` to the Supabase database
=> Recent senders

packages/app/features/send/screen.tsx, packages/app/features/send/suggestions/SendSuggestions.tsx, packages/app/features/send/suggestions/useTopSenders.ts, supabase/database-generated.types.ts, supabase/migrations/20250527225151_top_senders.sql
The PR introduces a new feature to display top senders in the send screen, adding a new query to fetch top senders data and modifying the SendSuggestions component.
- Added top senders query to fetch top senders data
- Modified SendSuggestions component to include top senders
- Created a new function useTopSenders to handle top senders query
- Added a new SQL function to calculate top senders based on send score
=> Top senders feed

packages/app/features/activity/ActivityAvatar.tsx, packages/app/features/home/TokenActivityFeed.tsx, packages/app/features/home/TokenActivityRow.tsx, packages/app/features/home/utils/useTokenActivityRowSize.ts, packages/app/utils/activity.test.tsx, packages/app/utils/activity.tsx
The PR introduces several UI changes to the token activity row, including the addition of a transfer direction indicator, changes to the activity avatar, and adjustments to the layout and styling of the token activity row.
- Added transfer direction indicator to activity avatar
- Changed activity avatar size and styling
- Adjusted token activity row layout and styling
- Updated amount formatting to include prefix for sent transfers
=> Token activity row UI changes

apps/expo/app/(tabs)/_layout.tsx
Updated the expo app header to match the web app's seamless design with left-aligned logo and background that blends with page content. This creates a unified, web-app-like experience across platforms.
- **Seamless Background**: Header background matches page content (no visual separation)
- **Left-Aligned Logo**: Logo positioned to the left like the web app
- **Theme Support**: Proper light/dark theme adaptation using tamagui tokens
- **Clean Code**: Consistent patterns and maintainable structure
**File**: `apps/expo/app/(tabs)/_layout.tsx`
**Before:**
```jsx
headerTitle: () => (
<XStack ai="center" jc="center">
<IconSendLogo size={'$2'} color={'$color12'} />
</XStack>
),
headerTitleAlign: 'center',
headerStyle: {},
```
**After:**
```jsx
const backgroundColor = theme.background || …
```
=> Native: align header with web

apps/expo/app/account/index.tsx, apps/expo/components/layout/ScreenContainer.tsx, packages/app/features/account/AccountScreenLayout.tsx, packages/app/features/account/components/AccountLinks.tsx, packages/app/features/account/components/AccountNavLink.tsx, packages/app/features/account/components/ShareProfileDialog.tsx
The PR introduces a new account screen layout, replacing the previous implementation with a more modular and flexible design. It also updates the ScreenContainer component to handle safe area insets and improves the AccountLinks component.
- Replaced account screen layout with MobileAccountLayout
- Updated ScreenContainer to handle safe area insets
- Improved AccountLinks component with new link handling
- Added error handling for QR code generation
- Updated AccountNavLink component to handle external links
=> Native: account screen

apps/expo/app/account/personal-info.tsx, packages/app/features/account/components/editProfile/screen.tsx, packages/app/features/account/components/personalInfo/screen.tsx
The PR introduces changes to the personal info screen, including the replacement of the Paragraph component with the PersonalInfoScreen component, and conditional rendering of the SettingsHeader based on the platform.
- Replaced Paragraph with PersonalInfoScreen
- Added conditional rendering for SettingsHeader
- Updated import statements
- Introduced Platform check for web
=> Native: personal info screen

apps/expo/app/account/affiliate.tsx, packages/app/features/affiliate/screen.native.tsx, packages/app/features/affiliate/screen.tsx
Created a native-specific implementation of the friends screen (`screen.native.tsx`) to enable proper functionality on React Native platforms while maintaining feature parity with the web version.
- `packages/app/features/affiliate/screen.native.tsx` - Native implementation of FriendsScreen
- **Before**: Used `RecyclerList` (web-optimized virtual scrolling)
- **After**: Implemented `FlatList` from React Native for native scrolling performance
- Added proper `renderItem`, `keyExtractor`, and `ListFooterComponent` props
- Configured `onEndReached` for infinite scroll with `onEndReachedThreshold={0.1}`
- **Removed**: `useReferrer()` hook integration (as requested for native)
- **Removed**: `useScrollDirection()` hook (replaced with FlatList's built-in scroll detection)
- **Removed**: …
=> Native: referrals screen

apps/expo/app/account/sendtag/add.tsx, apps/expo/app/account/sendtag/checkout.tsx, apps/expo/app/account/sendtag/first.tsx, apps/expo/app/account/sendtag/index.tsx, packages/app/features/account/sendtag/checkout/SendTagPricingDialog.tsx, packages/app/features/account/sendtag/first/FirstSendtagForm.tsx
The PR introduces new screens for sendtags, including add, checkout, and first sendtag screens, and improves the existing sendtags screen.
- Introduced new screens for sendtags
- Improved existing sendtags screen
- Added theme setting support
- Updated redirect behavior for native and web platforms
=> Native: sendtags screens

apps/expo/app/account/backup/confirm/[cred_id].tsx, apps/expo/app/account/backup/create.tsx, apps/expo/app/account/backup/index.tsx, packages/app/features/account/backup/confirm.tsx, packages/app/features/account/backup/create.tsx, packages/app/features/account/backup/index.tsx
The PR introduces passkeys screens for native applications, replacing previous placeholder screens.
- Introduce passkeys screens for native applications
- Replace placeholder screens with functional passkeys screens
- Update links to support pages
- Add platform-specific rendering for SettingsHeader
=> Native: passkeys screens

apps/expo/app/rewards/index.tsx, packages/app/features/explore/rewards/activity/screen.tsx
The PR introduces a new rewards screen with an ActivityRewardsScreen component, replacing the previous Paragraph component.
- Introduced ActivityRewardsScreen component
- Replaced Paragraph component with ActivityRewardsScreen
- Updated error message color in ActivityRewardsScreen
=> Native: rewards screen

apps/expo/app/(tabs)/explore/index.tsx, packages/app/features/explore/screen.tsx
The PR introduces a new ExploreScreen component and refactors the existing explore screen to use it. The new component includes a LinkBanner with a conditional href based on the platform.
- Introduced new ExploreScreen component
- Refactored existing explore screen to use ExploreScreen
- Added conditional href to LinkBanner based on platform
=> Native: explore screen

apps/expo/PLAN.md
The PR updates the documentation for the Expo app, including the navigation architecture, implementation plan, and known issues.
- Updates navigation architecture documentation
- Documents implementation plan and phases
- Lists known issues and planned improvements
=> Native: updated docs

packages/app/features/home/FriendsCard.tsx, packages/app/features/home/InvestmentsBalanceCard.tsx, packages/app/features/home/RewardsCard.tsx, packages/app/features/home/SavingsBalanceCard.tsx, packages/app/features/home/StablesBalanceList.tsx, packages/app/features/home/screen.tsx
- Update FriendsCard with better styling and layout
- Enhance InvestmentsBalanceCard with improved visual hierarchy
- Refine RewardsCard component styling
- Update SavingsBalanceCard with better spacing and typography
- Improve StablesBalanceList component layout
- Clean up home screen component structure and spacing
=> feat(home): Improve home screen card components

apps/next/pages/index.tsx
- Update Next.js home page to integrate with improved home components
- Ensure proper component mounting and responsive behavior
- Clean up page-level styling and layout
=> feat(home): Update home page integration

packages/app/features/home/TokenDetails.tsx
- Add comprehensive token action buttons (Buy, Sell, Send, Receive)
- Implement LinkableButton components with proper styling
- Add new icons (Plus, Minus, IconPlus, IconArrowUp) for actions
- Improve component layout with better spacing and responsive design
- Add hover effects and interaction states
- Enhance token information display with better visual hierarchy
=> feat(home): Major TokenDetails component enhancement

packages/app/components/icons/IconBadgeCheck.tsx, packages/app/features/account/sendtag/screen.tsx
The PR introduces changes to the `IconBadgeCheck` component and the `SendTagScreen` component. The `IconBadgeCheck` component has been simplified, and the `SendTagScreen` component now uses a shared content component to avoid duplication and provides different implementations for web and native platforms.
- Simplified `IconBadgeCheck` component
- Introduced shared content component in `SendTagScreen`
- Added web and native implementations for `SendTagScreen`
=> Native: main sendtag dialog

packages/app/features/account/sendtag/checkout/SendTagPricingDialog.tsx
The SendTagPricingDialog component has been refactored to improve its structure and functionality.
- Refactored SendTagPricingDialog component
- Added dialog content component to avoid duplication
- Improved web and native versions of the dialog
=> Native: sendtag pricing dialog

apps/expo/PLAN.md, apps/expo/app/(tabs)/activity/index.tsx, apps/expo/app/(tabs)/explore/index.tsx, apps/expo/app/(tabs)/send/confirm.tsx, apps/expo/app/investments/index.tsx, apps/expo/app/stables/index.tsx, apps/expo/app/token/index.tsx, apps/expo/components/layout/TabScreenContainer.tsx, packages/app/features/home/InvestmentBalanceList.tsx, packages/app/features/home/InvestmentsBalanceCard.tsx, packages/app/features/home/StablesBalanceCard.tsx, packages/app/features/home/StablesBalanceList.tsx, packages/app/features/home/screen.tsx, packages/snaplet/src/__tests__/models.test.ts
The PR introduces significant changes to the home screen navigation, including the addition of new screens for investments, stables, and token details. It also refactors existing code to improve performance and user experience.
- Added new screens for investments, stables, and token details
- Refactored home screen navigation to use stacking screens on native
- Improved performance and user experience
- Updated various components to use new navigation flow
=> Native: home screen navigation

apps/distributor/src/distributorv2.ts, apps/distributor/src/supabase.ts, packages/app/features/earn/hooks/index.ts, packages/app/features/explore/rewards/activity/screen.tsx, packages/app/utils/distributions.ts, supabase/database-generated.types.ts, supabase/migrations/20250706132108_refactor_send_earn_balances_timeline.sql, supabase/schemas/send_earn.sql, supabase/schemas/send_scores.sql
Refactor send earn balances timeline
Patch distributor for ebt refactor
Patch rewards screen for ebt refactor
=> Refactor send earn balances timeline

packages/app/features/send/confirm/screen.tsx, packages/app/features/swap/form/screen.tsx
Fixed issues with the CI build by modifying conditions for submitting transactions and updated styles for the swap form screen.
- Fixed submission conditions
- Updated swap form screen styles
=> Native: fixed CI build

packages/app/features/rewards/activity/screen.tsx, packages/app/features/rewards/components/DistributionClaimButton.tsx, packages/app/features/rewards/components/DistributionSelect.tsx
The PR introduces several UI fixes and enhancements to the rewards feature, including theme-aware color changes, layout adjustments, and icon replacements.
- Added theme-aware colors to various components
- Adjusted layouts for better responsiveness
- Replaced icons with text-based alternatives
- Improved code organization and readability
=> Native: rewards UI fixes

apps/expo/components/layout/ScreenContainer.tsx, apps/expo/components/layout/TabScreenContainer.tsx
The PR enhances the scrolling functionality in the ScreenContainer and TabScreenContainer components by adding support for scroll direction and content size change detection.
- Added useScrollDirection hook to ScreenContainer and TabScreenContainer
- Added ref, onScroll, and onContentSizeChange props to ScrollView in both components
- Added scrollEventThrottle prop to ScrollView in both components
=> Native: fixed fetching next pages

packages/app/features/home/StablesBalanceCard.tsx
Fixed home buttons shape by adding overflow hidden property.
- Added overflow hidden to LinkableButton components
- Updated StablesBalanceCardFooter to use new button styles
=> Native: fixed home buttons shape

apps/expo/PLAN.md, apps/expo/app/profile/[sendid]/index.tsx, apps/expo/components/layout/ScreenContainer.tsx, packages/app/features/activity/ActivityDetails.tsx, packages/app/features/profile/screen.tsx
The PR introduces several UI fixes and enhancements to the history page, including changes to the ScreenContainer, ActivityDetails, and ProfileScreen components. It also updates the PLAN.md file to reflect the completion of a task.
- Updated ScreenContainer to use Container from @my/ui
- Added safe area insets and padding to Container
- Changed ActivityDetails to remove elevation from XStack
- Updated ProfileScreen to use FlatList from react-native and added Platform check for SendButton
- Fixed history scroll issue
=> Native: history page UI fixes

packages/app/features/account/components/AccountLinks.tsx, packages/app/features/account/components/ShareProfileDialog.tsx, packages/app/features/profile/components/ProfileAboutTile.tsx
The PR introduces minor UI fixes, including adjustments to elevation and styling for web and mobile platforms.
- Updated `AccountLinks` component with padding
- Removed `Button` import in `ShareProfileDialog`
- Replaced `Button` with `PrimaryButton` in `ShareProfileDialog`
- Added border radius to `ProfileAboutTile` component
=> Minor UI fixes

apps/expo/app/(tabs)/activity/index.tsx, apps/expo/components/layout/TabScreenContainer.tsx, packages/app/components/SearchBar.tsx, packages/app/features/activity/RecentActivity.tsx, packages/app/features/activity/RecentActivityFeed.native.tsx, packages/app/features/activity/RecentActivityFeed.tsx, packages/app/features/activity/screen.tsx, packages/app/features/home/TokenActivityFeed.native.tsx, packages/app/features/home/TokenDetailsHeader.tsx, packages/app/features/swap/form/RiskDialog/SwapRiskDialog.tsx
The PR introduces several enhancements to the application, including optimized recent activity, improved layout, and new features.
- Optimized recent activity
- Improved layout for activity feed
- Added new features to the activity feed
- Updated token activity feed
- Improved token details header
=> Native: optimized recent activity

packages/app/features/affiliate/screen.native.tsx
The PR updates the FriendsScreen component to fix links and refactors the Referral type.
- Update Referral type to use get_friends
- Fix links in FriendsScreen using solito/link
- Add linkProps to FriendMobileRow
=> Native: fix friends screens links

apps/expo/PLAN.md, packages/app/features/swap/form/screen.tsx, packages/app/features/swap/summary/screen.tsx
The PR addresses accessibility issues in the trade feature by updating the pointerEvents property and changing router behavior for non-web platforms.
- Fixed accessibility issues with trades
- Updated pointerEvents property for web platform
- Changed router behavior for non-web platforms
=> Native: fixed accessibility issues with trades

packages/app/features/account/components/AccountNavLink.tsx
Updated AccountNavLink component with full width.
- Added full width to AccountNavLink component
=> Native: fixed account links arrows

packages/app/components/SearchBar.tsx, packages/app/features/activity/RecentActivityFeed.native.tsx
The PR introduces changes to the SearchBar component, including the addition of a containerProps property and the modification of the ThemeableStack elevation.
- Added containerProps property to SearchProps
- Modified ThemeableStack elevation
- Updated Search component to accept containerProps
=> Native: fixed elevation of search bar

apps/next/utils/seoHelpers.ts, docs/migration_reports/seo_migration_report.md
- Create seoHelpers.ts module with standardized SEO generation functions
- Add generateProfileTitle() and generateProfileDescription() for consistent profile SEO
- Add getProfileImageUrl() with fallback logic for profile images
- Add generateProfileSeoData() for complete profile SEO metadata generation
- Add PAGE_TITLES and PAGE_DESCRIPTIONS constants for common page patterns
- Improve consistency and reduce code duplication across profile pages
=> feat(seo): add SEO helper functions for common title and description patterns

apps/next/pages/profile/[sendid]/index.tsx
- Replace inline SEO title/description construction with generateProfileSeoData
- Use buildSeo to generate NextSeo configuration from profileSeoData
- Simplify code by removing repetitive declarations
- Ensure more consistent and maintainable SEO logic across profiles
=> refactor(profile): use SEO helpers and buildSeo in profile sendid page

packages/app/features/auth/sign-up/screen.tsx
- Add debounced form change handler to sync name input with URL
- Set initial form value from tag query parameter
- Improve user experience with real-time URL updates
- Depends on tag parameter management from previous PR
=> feat(auth): Add debounced form-URL sync for sendtag input

apps/next/public/.well-known/apple-app-site-association
Fixed Apple associated domains configuration in the Next app.
- Updated Apple app ID in webcredentials and applinks.
=> Native: fixed apple associated domains

packages/app/components/FormFields/IconAfter/IconAfter.native.tsx, packages/app/components/FormFields/IconAfter/IconAfter.tsx, packages/app/components/FormFields/IconBefore/IconBefore.native.tsx, packages/app/components/FormFields/IconBefore/IconBefore.tsx, packages/app/components/FormFields/NoteField.tsx, packages/app/components/FormFields/TextAreaField.tsx, packages/app/components/FormFields/TextField.tsx, packages/app/components/SearchBar.tsx, packages/app/features/account/components/personalInfo/screen.tsx, packages/app/features/account/sendtag/first/FirstSendtagForm.tsx, packages/app/features/auth/onboarding/screen.tsx, packages/app/features/auth/sign-up/screen.tsx, packages/app/features/send/SendAmountForm.tsx
Introduced new `IconBefore` and `IconAfter` components to handle icons in form fields, replacing previous implementations. Updated various form fields to use these new components.
- Introduced `IconBefore` and `IconAfter` components
- Replaced previous icon implementations in form fields
- Updated `NoteField`, `TextAreaField`, and `TextField` to use new icon components
=> Fixed icons issues in text fields

packages/app/features/send/suggestions/SendSuggestions.tsx
Fixed broken horizontal scroll in send suggestions on web by adjusting overflow style.
- Fixed horizontal scroll issue
- Updated overflow style for web platform
=> Fixed broken horizontal scroll in send suggestions on web

packages/app/features/profile/screen.tsx
The PR updates the `Vibes` component in the `screen.tsx` file to fix vibe icons.
- Update `Button.Text` size for different media sizes
- Replace `media.xxs` with `media.xs` for consistency
=> Native: fixed vibe icons

apps/expo/app/(auth)/_layout.tsx, packages/app/features/auth/layout.web.tsx, packages/app/features/auth/loginWithPhone/screen.tsx, packages/app/features/auth/onboarding/screen.tsx, packages/app/features/auth/sign-up/screen.tsx, packages/ui/src/components/FadeCard.tsx
The PR introduces several UI changes and enhancements to the authentication flow, including changes to the layout, form fields, and buttons. The changes aim to improve the overall user experience and make the authentication process more intuitive.
- Updated authentication layout to center content
- Changed form field styles and added icons
- Modified button styles and behavior
- Added FadeCard component for smoother transitions
- Updated text and labels for better clarity
- Removed Separator component
=> Auth UI changes

packages/app/components/SearchBar.tsx, packages/app/features/deposit/components/CopyAddressDialog.tsx
The PR introduces several UI changes to the `ConfirmSendDialog` and `CopyAddressDialog` components, including updated typography, colors, and layout adjustments.
- Updated dialog content and layout
- Changed button styles and typography
- Removed unused imports and variables
- Improved accessibility with added `testID` props
=> Some dialogs UI changes

packages/app/features/profile/screen.tsx
- Remove unused imports (ChevronLeft, useRouter, H2)
- Restructure layout hierarchy for better mobile/desktop experience
- Move banner to top level for improved visual hierarchy
- Adjust blur stack intensity based on banner image presence
- Reorganize component structure for cleaner responsive design
=> feat: improve profile screen layout and responsiveness

packages/app/features/home/TokenDetailsHeader.tsx
Changed the order of token trade buttons in the TokenDetailsHeader component.
- Changed order of Buy and Sell buttons
=> Changed order of token trade buttons

packages/app/features/affiliate/screen.native.tsx, packages/app/features/affiliate/screen.tsx, supabase/database-generated.types.ts, supabase/migrations/20250805100246_add_name_to_get_friends.sql, supabase/schemas/referrals.sql
Improved labels on referrals screen by adding name and sendid to get_friends function.
- Added name to get_friends function
- Added sendid to get_friends function
- Updated label to use referral tag or name/sendid
- Updated link href to use referral tag or sendid
- Updated database schema to include name and sendid
=> Improved labels on referrals screen

packages/app/features/home/InvestmentsBalanceCard.tsx, packages/app/features/home/StablesBalanceCard.tsx, packages/app/features/home/screen.tsx
The PR introduces several UI changes and improvements to the Investments Balance Card and Stables Balance Card.
- Added new components for Investments Balance Card
- Improved toggleSubScreen functionality
- Updated Stables Balance Card actions
- Introduced new Separator component
=> Small UI changes in invest card

packages/app/features/home/InvestmentsBalanceCard.tsx, packages/app/features/home/SavingsBalanceCard.tsx
Improved home screen loaders by adjusting spinner alignment and updating savings balance card text.
- Adjusted spinner alignment in InvestmentsBalanceCard
- Updated savings balance card text to handle apyData
=> Improve home screen loaders

apps/expo/eas/post-install, apps/expo/eas/pre-install
The PR enhances the EAS hooks to work on every shell by adjusting the PATH and verifying tool installations.
- Added functions to check for command existence and find tools
- Updated PATH to include required directories
- Verified installations of Foundry and Bun
- Improved error handling for tool installations
- Added shell configuration detection and persistence
=> Native: adjusted EAS hooks to work on every shell

packages/app/utils/getRpId.ts
Modified the getRpId function to return static values for ios and android.
- Updated getRpId function
- Removed applicationId import
- Replaced dynamic ids with static 'send.app' for ios and android
=> Native: made rp id static

packages/app/components/FormFields/CountryCodeField.tsx
The PR introduces performance improvements for the country field in the native application. 
It replaces the previous country selection component with a FlatList, which is more efficient for large lists of countries.
- Replaces previous country selection component with FlatList
- Improves performance for large lists of countries
- Adds CountryItem component for country list items
- Implements handleCountrySelect callback for country selection
=> Native: performance improvements for country field

packages/app/features/account/backup/confirm.tsx, packages/app/features/account/backup/create.tsx, packages/app/features/account/backup/index.tsx
The PR introduces several UI fixes and improvements for the passkeys screen on Android, including layout adjustments, button styling, and form handling.
- Adjusted layout for AddPasskeySigner component
- Improved button styling for Android
- Updated form handling for RemovePasskeyConfirmation
- Added Android-specific height handling
- Changed button variants to PrimaryButton
=> Native: passkeys screen fixes for android

packages/app/features/account/sendtag/add/AddSendtagsForm.tsx
Added fieldsetProps to improve the AddSendtagsForm layout.
- Added fieldsetProps for full-width input
=> Native: sendtags screen fixes for android

packages/app/features/deposit/DepositCoinbase/DepositCoinbaseForm.tsx, packages/app/utils/useCoinbaseOnramp.native.ts
The PR introduces fixes for deposit screens on Android, including adjustments to form height handling and modifications to the Coinbase onramp URL.
- Update form height handling for Android
- Modify Coinbase onramp redirect URL
- Add browser settings for onramp URL
=> Native: deposit screens fixes for android

packages/app/features/home/InvestmentBalanceList.tsx, packages/app/features/home/screen.tsx
Hey Kolwaii, can you summarise this PR?
=> Native: investments screen fixes for android

packages/app/features/home/StablesBalanceList.tsx
The PR introduces minor layout adjustments to improve the stables screen on Android.
- Added line height to Paragraph component
- Removed flex property from XStack component
=> Native: stables screen fixes for android

packages/app/features/home/TokenActivityFeed.native.tsx, packages/app/features/home/TokenDetailsHeader.tsx
The PR introduces several UI enhancements and fixes for the token details screen on Android, including adjustments to elevation, positioning, and styling of various components.
- Added elevation to XStack component
- Introduced a new XStack component with absolute positioning
- Removed elevation from YStack component
- Updated Card component with consistent elevation
- Changed elevation of QuickActionButton component
=> Native: token details screen fixes for android

packages/app/features/auth/components/Carousel.native.tsx
The PR introduces a new carousel component for the splash screen, featuring animated progress and item navigation.
- Adds a new Carousel component
- Implements animated progress for carousel items
- Includes navigation between carousel items
=> Native: optimize carousel on splash screen

apps/expo/app/_layout.tsx
The PR enhances the native app by fixing the white blink issue when moving between screens on Android and adds dynamic background color based on the system's color scheme.
- Fix white blink issue on Android
- Add dynamic background color
- Use system's color scheme
=> Native: fix white blink when moving between screens on android

packages/app/features/earn/rewards/screen.tsx, packages/app/features/home/TokenDetails.tsx, packages/app/features/home/TokenDetailsHeader.tsx, packages/app/features/home/TokenQuickActions.tsx
Refactored token details UI to improve organization and add key metrics display.
- Refactored `TokenDetailsHeader` component to focus on displaying token balance and price information
- Extracted quick action buttons (Buy, Sell, Add Money, Withdraw) into a new `TokenQuickActions` component
- Added a new `TokenKeyMetrics` component to the token details page
- Improved the display of token balance information to show USD value as the primary figure with 24h change
- Enhanced the market data display with better formatting and styling for price change indicators
- Reorganized imports for better code organization
1. Navigate to a token details page for both a regular token and a stablecoin
2. Verify that the token balance displays correctly with the USD value as the primary figure
3. Check …
=> feat: token details balance refactor

packages/app/features/activity/RecentActivity.tsx, packages/app/features/activity/RecentActivityFeed.native.tsx, packages/app/features/home/TokenActivity.tsx, packages/app/features/home/TokenActivityFeed.native.tsx
The PR introduces several improvements to the activity lists, including increasing the page size, adding a loader, and modifying the UI components.
- Increased page size to 50
- Added a loader for fetching next page
- Modified DateSeparatorRow component
- Updated TokenActivityFeed component
=> Native: activity lists improvements

packages/app/components/FormFields/NoteField.tsx
The PR fixes the note field on Android by introducing Android-specific height management and overriding props for proper layout behavior.
- Fixed note field on Android
- Introduced Android-specific height management
- Overrode props for proper layout behavior on Android
- Maintained existing behavior on iOS and web
=> Native: fixed note field on android

packages/app/features/profile/components/ProfileHeader.tsx
Fixed clipped content issue in profile header on Android.
- Fixed profile header clipped content on Android
=> Native: fixed profile header clipped content on android

apps/expo/app/profile/[sendid]/history.tsx
Fixed send button position on history screen for Android.
- Fixed send button position on Android history screen
=> Native: fixed send button position on history screen on android

docs/coingecko.md
docs: add CoinGecko integration ([coingecko.md](http://coingecko.md))
docs: append change record (doc-comment, commit list, PR link placeholder) to [coingecko.md](http://coingecko.md)
=> docs: add CoinGecko integration (coingecko.md)

apps/expo/app/token/index.tsx, packages/app/features/home/TokenDetails.tsx
The PR updates the TokenDetails component to fix scrolling issues on Android and modifies the TokenScreen to render TokenDetails without passing the coin prop.
- Updated TokenDetails component
- Modified TokenScreen rendering
- Fixed Android scrolling issue
=> Native: fixed token details page not scrolling on android

packages/app/features/profile/VibeButton.native.tsx, packages/app/features/profile/VibeButton.tsx, packages/app/features/profile/screen.tsx
The PR introduces a new `VibeButton` component and refactors the existing `ProfileScreen` to use it, improving the overall user experience.
- Introduced new `VibeButton` component
- Refactored `ProfileScreen` to use `VibeButton`
- Removed unused `LinkableButton` import
- Improved code organization and readability
=> Native: fixed vibe button navigation crushing android app

packages/app/features/send/confirm/ConfirmScreenAvatar.native.tsx, packages/app/features/send/confirm/ConfirmScreenAvatar.tsx, packages/app/features/send/confirm/screen.tsx
The PR introduces a new component `ConfirmScreenAvatar` to handle avatar display and navigation on the confirm screen, fixing the issue of the android app crashing.
- Introduced new component `ConfirmScreenAvatar` for avatar display and navigation
- Fixed android app crash issue on confirm screen
- Removed redundant avatar code from `screen.tsx`
=> Native: fixed confirm screen avatar navigation crushing android app

packages/app/features/profile/history/screen.tsx, packages/app/features/send/confirm/screen.tsx, packages/app/features/send/confirm/useRedirectAfterSend.native.ts, packages/app/features/send/confirm/useRedirectAfterSend.ts
The PR introduces several improvements to the profile history screen and send confirmation screen. 
It fixes the post sending navigation issue on Android, improves the layout and design of the profile history screen, 
and enhances the send confirmation screen with a redirect feature after sending.
- Improved profile history screen layout
- Fixed post sending navigation issue on Android
- Enhanced send confirmation screen with redirect feature
- Removed Platform.OS checks for SendButton
- Introduced useRedirectAfterSend hook
=> Native: fixed post sending navigation crushing android app

packages/api/src/routers/auth/router.ts, packages/app/features/auth/appReviewLogin/useAppReviewSignIn.ts
Moved review sign in logic to backend, adding a new API endpoint to handle sign in with password, bypassing captcha.
- Added new API endpoint for app review sign in
- Modified useAppReviewSignIn to use new API endpoint
- Removed captcha from sign in process
- Updated error handling for sign in
- Improved security with admin client
=> Native: moved review sign in logic to backend

packages/app/features/home/TokenChartSection.tsx, packages/app/features/home/TokenDetailsHeader.tsx, packages/app/features/home/TokenKeyMetrics.tsx, packages/app/features/home/screen.tsx
The PR updates the UI components to use XStack instead of Paragraph for change badges, 
providing a consistent design and improved styling.
- Replaced Paragraph with XStack for change badges
- Updated change badge styling for consistency
- Improved theme support for change badges
=> Native: fixed border radius for all ios invest returns

packages/app/features/profile/screen.tsx
Fixed vibes encoding on native by removing encodeURIComponent.
- Removed encodeURIComponent for note
=> Native: fixed vibes encoding on native

packages/app/components/SearchBar.tsx, supabase/database-generated.types.ts, supabase/migrations/20250921171543_add_is_verified_to_tag_search.sql, supabase/schemas/tags.sql, supabase/schemas/types.sql, supabase/tests/tags_search_test.sql
Added `is_verified` field to search results, updated database schema and search function.
- Added `is_verified` field to `tag_search_result` type
- Updated `tag_search` function to include `is_verified` field
- Modified database schema to include `is_verified` field
- Updated tests to reflect changes
=> Added is_verified to search results

apps/expo/babel.config.js, apps/expo/components/layout/StackNavigator.tsx, apps/expo/components/layout/TabScreenContainer.tsx
The PR improves Android performance by optimizing the StackNavigator and TabScreenContainer components. It also updates the babel configuration to include the @tamagui/babel-plugin for all platforms.
- Improve StackNavigator performance on Android
- Optimize TabScreenContainer for Android
- Update babel configuration for @tamagui/babel-plugin
=> Native: improve android performance

packages/app/utils/useUser.ts
The PR introduces several improvements to the `useUser` hook, including memoization and stability during navigation. It also replaces the `useRouter` hook with `useReplace` and adds error handling for token validation and profile fetching.
- Memoized `useUser` hook for improved performance
- Replaced `useRouter` with `useReplace` for navigation
- Added error handling for token validation and profile fetching
- Improved code organization and readability
=> Native: memoized useUser and made it stable during navigation

packages/app/features/home/TokenActivityRow.tsx
The TokenActivityRow component has been refactored to improve performance by utilizing memoization.
- Refactored TokenActivityRow component
- Added memoization to TokenActivityRowContent
- Replaced useRouter with usePush
- Improved handlePress function with useCallback
=> Native: memoized TokenActivityRow

packages/app/components/SearchBar.tsx, packages/app/features/rewards/activity/screen.tsx, packages/app/features/rewards/components/CantonWalletForm.tsx, packages/app/features/rewards/components/CantonWalletStatus.tsx, packages/app/utils/useUser.ts, packages/app/utils/zod/cantonWallet.ts, packages/snaplet/.snaplet/dataModel.json, packages/snaplet/.snaplet/snaplet-client.d.ts, packages/snaplet/.snaplet/snaplet.d.ts, supabase/database-generated.types.ts, supabase/migrations/20250930114000_create_canton_party_verifications.sql, supabase/schemas/canton_party_verifications.sql
This PR introduces Canton wallet address verification, allowing users to verify their Canton wallet addresses and enabling the display of verification status. It adds a new table to the database for storing Canton wallet verifications and implements Row Level Security (RLS) policies for secure data access.
- Added Canton wallet address verification functionality
- Created `CantonWalletForm` and `CantonWalletStatus` components
- Updated `ActivityRewardsScreen` to display verification status
- Added database schema for storing Canton wallet verifications
- Implemented Row Level Security (RLS) policies for secure data access
=> Canton wallet address verification

packages/app/features/rewards/activity/screen.tsx, packages/app/features/rewards/components/CantonWalletStatus.tsx
The PR introduces changes to the Canton wallet verification process, including a minimum balance requirement and a new condition to connect the Canton wallet.
- Added minimum Canton wallet balance requirement
- Introduced a new condition to connect the Canton wallet
- Updated the DistributionRequirementsCard component
- Modified the CantonWalletStatus component
=> Lower canton wallet verification min balance
