0xsend/sendapp

- apps/next/pages/distributions.tsx
- packages/playwright/tests/distributions.logged-in.spec.ts
This PR just adds the existing distribution screen as a page. No major changes
> Add Distributions page to regain parity with send web mvp

- packages/app/components/HomeHeader.tsx
- packages/app/components/sidebar/HomeSideBar.tsx
- packages/app/features/home/screen.tsx
- packages/app/routers/params.tsx
- packages/ui/src/components/BottomSheet.tsx
Adds logic for bottom sheet on mobile. Uses url state instead of context
Not 100% happy with the naming of everything, probably will take some time to rethink
This PR depends on #28 and #41
> Home Bottom Sheet for mobile

- apps/next/pages/sign-in.tsx
- packages/app/components/sidebar/SignInSideBar.tsx
- packages/app/features/auth/AuthCarouselContext.tsx
- packages/app/features/auth/layout.web.tsx
- packages/app/features/auth/sign-in-screen.tsx
- packages/app/utils/getPlaiceholderImage.ts
- packages/ui/src/components/SideBar/index.tsx
To have the image display behind the sidebar, we need it to render in the layout component. Context lets us render the images in layout, while controlling them in the page
> Use context to share auth images between pages and layouts

- packages/app/components/icons/IconLogout.tsx
- packages/app/components/sidebar/HomeSideBar.tsx
- packages/app/components/sidebar/SideBarNavLink.tsx
- packages/app/features/account/changePhone.tsx
- packages/app/features/account/components/editProfile/screen.tsx
- packages/app/features/account/components/uploadProfileImage/screen.tsx
- packages/app/features/auth/components/VerifyCode.tsx
- packages/app/features/auth/onboarding/screen.tsx
- packages/app/features/leaderboard/screen.tsx
- packages/app/utils/distributions.ts
Fixed 99% of the warnings thrown by the linter about unused variables/ imports
Also fixed errors about missing imports for SecretStore
One lint warning remains in the useSendAccountBalances hook. It is calling a react hook in a for loop, which is problematic and can cause unexpected crashes. This necessitates a refactor, which I will submit in a future PR
> Fix linter errors/warnings

- packages/app/features/account/earn-tokens/screen.tsx
- packages/app/routers/params.tsx
For now I'm keeping the name "distribution" in the codebase
We should try to maintain parity between the codebase and the marketing. Once we settle on the new name for "distributions", I will update our variable and component names to match
> EarnList and Distribution Query Param

- packages/app/features/account/earn-tokens/components/DistributionClaimButton.tsx
- packages/app/features/account/earn-tokens/screen.tsx
Most of the work toward distribution rewards page for wide screen and tablet.
Still some todos for later PRs:
TODOs:
- Send Token Balance on base
- mobile support
- update edge case styles for claim button
- Double check claim button will work with Base migration
- carrot above selected distribution in list
- Fix incorrect flexbox and padding in some areas
- Light Mode styles
> Distribution Rewards page general layout and data

- packages/app/components/TopNav.tsx
Noticed our TopNav text in light mode was a little dim
Checked styles and noticed it was 25% too dim. Fixed
> Brighten TopNav text color

- apps/distributor/src/distributor.test.ts
- packages/api/src/routers/tag.ts
- packages/app/features/account/sendtag/checkout/checkout-utils.tsx
- packages/app/features/account/sendtag/checkout/components/checkout-confirm-button.tsx
- packages/app/utils/hexToPgBase16.test.ts
- packages/app/utils/hexToPgBase16.ts
- packages/app/utils/pgBase16ToHex.test.ts
- packages/app/utils/pgBase16ToHex.ts
- supabase/migrations/20240424041809_add_send_revenues_safe_receives_rls_select_policy.sql
- supabase/tests/tags_confirmation_test.sql
- Use the send_revenues_safe_receives table to validate tag purchases instead of fetching event logs from the blockchain
- Add hexToPgBase16 and pgBase16ToHex utility functions for converting between hex and Postgres base16 formats
- Update useSenderSafeReceivedEvents hook to fetch data from send_revenues_safe_receives table
- Modify lookupSafeReceivedEvent function to use the send_revenues_safe_receives data for validation
- Add tests for hexToPgBase16 and pgBase16ToHex utility functions
- Add test case to ensure duplicate receipt hashes do not confirm tags
> refactor: use send_revenues_safe_receives table to validate tag purchases

- packages/app/features/home/screen.tsx
Adds Sendtag info to the side of the deposit button
This page is starting to get a little messy, like TopNav
If we plan to have a lot of screens that are side by side on desktop, and different pages on mobile, we should dedicate some time building a custom component for that purpose
Next Pages Router really isn't built well for pages like this. We should make a component that helps us achieve these subscreens with query params
> Show text about Sendtag on home screen

- .snaplet/snaplet-client.d.ts
- .snaplet/snaplet.d.ts
- packages/playwright/tests/onboarding.logged-in.spec.ts
- packages/shovel/etc/config.json
- packages/shovel/src/index.ts
- packages/shovel/src/integrations/index.ts
- packages/shovel/src/integrations/send-account-created.ts
- packages/shovel/src/integrations/send-account-signing-key-added.ts
- packages/shovel/test/__snapshots__/index.test.ts.snap
- supabase/database-generated.types.ts
- supabase/migrations/20240425030525_add_send_account_signing_key_added.sql
Starts the backend integration for managing keys and eventually adding backup signers to your send account.
> shovel: add send_account_signing_key_added

- apps/aabundler/README.md
- packages/app/features/account/sendtag/checkout/components/checkout-confirm-button.tsx
- packages/app/utils/userop.ts
- packages/contracts/.gitignore
- packages/contracts/README.md
- packages/contracts/script/UpdateTokenPaymasterCachedPrice.s.sol
This was discovered during testnet when the bundler validates the validUntil for both the sender and the paymaster (if set).
The token paymaster sets the valid until to the last price update + max age. Perhaps, this needs to be automated if the postOp does not update during normal operations.
> contracts: add UpdateTokenPaymasterCachedPriceScript

- packages/app/features/send/components/SendSearch.tsx
- packages/playwright/tests/activity.onboarded.spec.ts
- packages/playwright/tests/profile.onboarded.spec.ts
I enabled `activity.onboarded` 'can search on activity page' because it's passing locally even though I didn't change anything in the test itself. If there was another reason it was skipped, just let me know and I can update that.
> update playwright tests

- packages/contracts/package.json
- packages/contracts/script/DeploySendtagCheckout.s.sol
- packages/contracts/script/anvil-add-sendtag-checkout-fixtures.ts
- packages/contracts/src/Helper.sol
- packages/contracts/src/SendtagCheckout.sol
- packages/contracts/test/DeploySendtagCheckout.t.sol
- packages/contracts/test/SendtagCheckout.t.sol
- packages/wagmi/src/generated.ts
- tilt/infra.Tiltfile
Introduced a new smart contract `SendtagCheckout` for handling ERC20 token payments within the Sendtag ecosystem, along with comprehensive tests for its functionality. This contract manages transactions involving multisigs and referrer bonuses.
- Added `SendtagCheckout.sol` contract.
- Handles payments and bonuses within the Sendtag system.
- Includes functions for toggling operational status and withdrawing tokens or ETH.
- Implemented tests in `SendtagCheckout.t.sol`.
- Test coverage includes various scenarios for the `checkout` function, withdrawal operations, and the toggle mechanism.
- Updated `wagmi/src/generated.ts` with the new contract's ABI and related definitions.
1. Deploy the `SendtagCheckout` contract on a testnet or local blockchain environment.
2. Run the tests provided in …
> add SendtagCheckout contracts

- packages/contracts/src/SendtagCheckout.sol
- packages/contracts/test/SendtagCheckout.t.sol
- packages/wagmi/src/generated.ts
https://github.com/0xsend/sendapp/pull/603
https://github.com/0xsend/sendapp/pull/592
> contracts: bonus -> rewards

- packages/playwright/tests/account-sendtag-checkout.onboarded.spec.ts
- packages/playwright/tests/fixtures/checkout/page.ts
- packages/shovel/etc/config.json
- packages/shovel/src/integrations/send-account-transfers.ts
- packages/shovel/test/__snapshots__/index.test.ts.snap
- supabase/migrations/20240728180824_delete_duplicate_send_account_created_account_index.sql
- supabase/migrations/202407281808278_send_account_transfers_filter_non_send_accounts.sql
- supabase/tests/send_account_transfers_test.sql
* supabase cleanup
drop duplicate send_account_created index
enable pg_cron
create cronjob for deleting send account transfers with no send account created row
* add delete send account transfers with no send account
* go back to indexing all USDC an SEND token transfers
* just filter the rows actually
* fix checkout specs to be less flaky
> bb/supabase cleanup (#634)

- packages/app/features/leaderboard/screen.tsx
Designs for leaderboard.
(tests and real data will be in separate prs)
> leaderboard designs

- packages/app/features/leaderboard/__snapshots__/screen.test.tsx.snap
- packages/app/features/leaderboard/screen.test.tsx
- packages/app/features/leaderboard/screen.tsx
- packages/playwright/tests/leaderboard.logged-in.spec.ts
Just the basics until we get dat data
> leaderboard tests

- packages/app/features/auth/sign-up/sign-up-form.tsx
- packages/app/features/splash/screen.tsx
- packages/ui/src/components/NativeToast.tsx
The error is in a 10 second long toast. The toast is hidden after component unmounts so it doesn't stay up there after a successful login.
> login errors

- packages/app/features/auth/sign-up/sign-up-form.tsx
UI part of the ticket https://3.basecamp.com/5743564/buckets/36023883/todos/8021528909
checked out off https://github.com/0xsend/sendapp/pull/864
> Handle already used phone in UI

- packages/app/features/auth/sign-up/sign-up-form.tsx
Changed condition to show backing up page on sign-up route from checking if error is instance of DOMException to checking if error's constructor's name is DOMException. From business logic perspective it's gonna be the same as this is the only error with the given name that will occur in the system, but this setup is easier to mock from web-authenticator
> Adjust condition to show backing up page

- packages/app/features/home/screen.test.tsx
- packages/contracts/test/TokenPaymaster6.t.sol
- supabase/migrations/20241223152609_update_profile_lookup_public_phone_number.sql
- supabase/tests/profile_lookup_test.sql
- tilt/tests.Tiltfile
You can hide your phone number now by marking your profile as public. Previously, all profiles could be found if you know the phone number of the user.
> feat(supabase): Update profile lookup by phone number

- .github/workflows/ci.yml
Turning off playwright in branches because 90% of the time they fail and aren't helpful. Should ensure they run in local, dev, or main
> Stop running playright tests in previews

- packages/app/features/account/rewards/activity/screen.tsx
- packages/app/utils/dateHelper.test.ts
- packages/app/utils/dateHelper.ts
- packages/snaplet/README.md
- packages/snaplet/snaplet.config.ts
- supabase/database-generated.types.ts
- supabase/migrations/20250102214349_update_distribution_verifications_summary_for_pending_send_streak.sql
Instead of showing completed, send streak will show ongoing while in the middle of distribution qualification. It uses `created_at` on the distribution verification for checking when the streak was last reached.
> fix(app): send streak shows ongoing

- packages/app/features/account/rewards/activity/screen.tsx
- packages/app/utils/dateHelper.test.ts
- packages/app/utils/dateHelper.ts
- packages/snaplet/README.md
- packages/snaplet/snaplet.config.ts
- supabase/database-generated.types.ts
- supabase/migrations/20250102214349_update_distribution_verifications_summary_for_pending_send_streak.sql
Instead of showing completed, send streak will show ongoing while in the middle of distribution qualification. It uses `created_at` on the distribution verification for checking when the streak was last reached.
> fix(app): send streak shows ongoing (#989)

- apps/next/pages/index.tsx
**Issue**: When user logout and login again on the same or different account, while home screen is loading there is no loader shown, instead there is a no send account message displayed
**root cause**: After user is signed out some parts of the application are refreshing send account query (before redirected to the splash screen), no results will be returned because user is signed out, null value will be stored in query cache. When logging in back again, this cache is still there, so account query is not in loading state, and also there is no data. Thats the reason no account message is shown.
**implemented solution**: when splash screen is shown, session is for sure gone, then cancel all ongoing account queries and remove query cache as it is invalid anyway
> Fix no account bug after logout

- packages/app/features/activity/__snapshots__/screen.test.tsx.snap
- packages/app/features/home/HomeButtons.tsx
playwright for some reason ignores element with this prop `animation="200ms"`
> Fixing send tests

- apps/distributor/src/app.ts
- apps/distributor/src/distributorv2.test.ts
- apps/distributor/src/distributorv2.ts
- apps/distributor/src/supabase.ts
- apps/distributor/src/wagmi.ts
- packages/api/src/routers/distribution.ts
- packages/app/components/MobileButtonRowLayout.tsx
- packages/app/features/account/rewards/components/DistributionClaimButton.tsx
- packages/app/utils/distributions.ts
- packages/contracts/script/anvil-add-send-merkle-drop-fixtures.ts
- packages/snaplet/.snaplet/dataModel.json
- packages/workflows/src/distribution-workflow/wagmi.ts
- supabase/database-generated.types.ts
- supabase/migrations/20250126191544_add_tranche_id_to_distributions.sql
- supabase/tests/distribution_hodler_addresses_test.sql
- supabase/tests/distributions_test.sql
- tilt/infra.Tiltfile
This was a miss when deploying the new send token merkle drop for the send token upgrade.
The tranche starts at 3 since we reused the base merkle drop contract when migrating to Base.
We are going to use tranche ID 3 for the new send token merkle drop contract for distribution 11 after the send token upgrade.
> feat: add tranche_id to distributions

- packages/app/features/send/confirm/screen.tsx
Removed the hasBeenLongEnough check in the confirm screen, which was used to determine if a transaction had been pending for too long.
- Removed hasBeenLongEnough variable
- Updated conditional statement to remove hasBeenLongEnough check
- Removed logging related to hasBeenLongEnough
> Remove hasBeenLongEnough in confirm screen

- packages/app/utils/formatAmount.test.ts
- packages/app/utils/formatAmount.ts
Changed the `formatAmount` utility to use floor instead of rounding when formatting decimal numbers to avoid displaying values larger than what's actually available.
- Changed `formatAmount` to floor decimal values
- Updated test cases to reflect new flooring behavior
- Ensures accurate display of financial amounts
> use floor in formatAmount to avoid round up

- packages/app/features/account/rewards/activity/screen.tsx
The PR introduces a null check for `sendSlash` to prevent undefined reference errors and improve code reliability. It also simplifies conditional logic and improves handling of incomplete distribution data.
- Added null check for `sendSlash`
- Improved handling of incomplete distribution data
- Simplified conditional logic
> Hide progress when no send_slash exists

- packages/app/components/MobileButtonRowLayout.tsx
- packages/ui/src/utils/useSafeAreaInsets.ts
The PR simplifies the `useSafeAreaInsets` hook, removes the `isPwa` check in `MobileButtonRow`, and adjusts the memoized safe area insets.
- Simplified `useSafeAreaInsets` hook
- Removed `isPwa` check in `MobileButtonRow`
- Updated `pb` prop in `MobileButtonRow` to a fixed value
> Adjust memoized safe area insets

- packages/ui/src/components/NativeToast.tsx
Added safe area margin to NativeToast component for proper display on various devices.
- Added safe area margin for Toast
- Imported useSafeAreaInsets utility
- Updated NativeToast component with safe area inset
> add safe area margin for Toast

- packages/ui/src/utils/useSafeAreaInsets.ts
The PR fixes Server-Side Rendering (SSR) problems for safe area insets by initializing the state with default values and updating the insets only when the component is rendered on the client-side. It also improves handling of undefined window object and adds a delay to ensure CSS is loaded before updating insets.
- Fix SSR problems for safe area insets
- Initialize state with default values
- Update insets only on client-side rendering
- Improve handling of undefined window object
- Add delay to ensure CSS is loaded before updating insets
> fix SSR problems for safe area insets

- packages/ui/src/utils/usePwa.ts
The PR refactors the `usePwa` function to be a hook, utilizing React's `useState` and `useEffect` to improve PWA detection for iOS and Android.
- Refactor `usePwa` to be a hook
- Utilize `useState` and `useEffect` for PWA detection
- Add event listener for display mode changes
- Improve PWA detection for iOS and Android
> Refactor usePwa to be a hook

- supabase/migrations/20250225053238_patch_send_ceiling_trigger_repeated_sends.sql
The PR introduces a new trigger function `insert_verification_send_ceiling` to handle send ceiling verification for users.
- Introduces a new trigger function `insert_verification_send_ceiling`
- Updates existing verification records
- Creates new verification records
- Handles send ceiling calculation
- Includes error handling for exceptions
> Patch send ceiling trigger repeated sends

- packages/app/utils/useSendAccountBalances.ts
The PR fixes the USDC conversion rate by using a 1-to-1 price.
- Fix USDC conversion rate to 1-to-1
- Update useSendAccountBalances to use fixed USDC price
> fix usdc conversion rate

- .github/workflows/ci.yml
- packages/playwright/tests/fixtures/profiles/test.ts
- packages/playwright/tests/fixtures/sendtags/checkout/page.ts
- packages/playwright/tests/profile.anon.spec.ts
- packages/playwright/tests/profile.logged-in.spec.ts
- packages/playwright/tests/profile.onboarded.spec.ts
This PR improves the stability of tests in the Playwright framework by introducing more robust expectations and waits. It also increases the timeout for waiting for Tilt to be ready in the CI workflow.
- Improved test stability with more robust expectations
- Added waits for page URLs to ensure correct navigation
- Increased timeout for waiting for Tilt in CI workflow
- Updated test code to use async/await for better readability
> fix(playwright): more stable tests

- packages/app/data/sendtags.test.ts
- packages/app/data/sendtags.ts
Affiliates now receive 25% of the sendtag total.
> fix: Update Sendtag rewards and calculations to reflect new reward structure

- supabase/migrations/20250328184405_fix_temporal_activity_handler.sql
The PR introduces a fix for the temporal activity handler by creating indexes on the `send_account_transfers` table and implementing a trigger function to delete older temporal send account transfers.
- Create indexes on `send_account_transfers` table
- Implement trigger function to delete older temporal send account transfers
- Prevent duplicate activities once a transfer is completed
> Fix temporal activity handler

- packages/playwright/tests/swap.onboarded.spec.ts
The PR reduces the number of pairs being swapped in the playwright tests by limiting the input coins to only `usdcCoin`.
- Decrease input coins in swap tests
- Remove unused coin imports
- Limit swap pairs to only `usdcCoin`
> Decrease pairs being swapped in playwright

- packages/workflows/src/utils/index.ts
- packages/workflows/src/utils/startWorkflow.ts
adds a util function to make calling workflows more typesafe.
expects the function name as the id
> add startWorkflow util for type safe args and ids

- packages/app/data/coins.ts
- packages/app/features/home/TokenBalanceList.tsx
- packages/app/features/home/TokenDetails.tsx
- packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap
The PR introduces a new optional field `shortLabel` to the coin schema, and updates the token labels to use the `shortLabel` if available. It also removes the uppercase transformation from the token labels.
- Added `shortLabel` field to coin schema
- Updated token labels to use `shortLabel` if available
- Removed uppercase transformation from token labels
- Updated coin data with `shortLabel` values
> Lowercase token names on home page

- packages/app/components/MobileButtonRowLayout.tsx
- packages/app/features/home/HomeQuickActions.tsx
- packages/app/features/home/TokenDetails.test.tsx
- packages/app/features/home/TokenDetails.tsx
- packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap
- packages/app/features/home/screen.tsx
The PR introduces a new component `HomeQuickActions` that provides quick actions on the home screen for mobile devices. It includes two buttons for deposit and trade. The component is used in `TokenDetails` and `HomeBody` components. The PR also refactors the existing code to remove duplicated logic and improve the user experience.
- Added `HomeQuickActions` component
- Refactored `TokenDetails` component
- Updated `HomeBody` component
- Removed duplicated logic
- Improved user experience
> Add quick actions on home screen on mobile

- packages/app/features/swap/form/screen.tsx
The PR updates the swap form screen to use KyberSwap prices as a fallback to CoinGecko and DexScreener. It also adds USD amount displays for input and output amounts.
- Update `useTokenPrices` hook to `isLoadingPrices`
- Add USD amount displays for input and output amounts
- Update conditional statements to handle loading states and price availability
- Improve code readability and consistency
> Use kyberswap prices in trade as fallback to coingecko and dexscreener

- packages/app/features/profile/__snapshots__/screen.test.tsx.snap
- packages/app/features/profile/screen.tsx
- packages/app/features/send/SendAmountForm.tsx
- packages/app/features/send/__snapshots__/screen.test.tsx.snap
- packages/app/features/send/confirm/screen.tsx
Increased font size of notes to match iMessage in multiple screens.
- Increased notes font size in profile screen
- Updated notes font size in send amount form
- Changed notes font size in send confirm screen
> Increased notes font size to match iMessage

- packages/app/components/sidebar/HomeSideBar.tsx
The PR updates the sidebar menu icons on desktop, replacing some icons and adjusting their sizes and scales.
- Replaced `IconActivity` with `IconArrowUp`
- Updated icon sizes and scales for better alignment
- Changed `IconHome` size to `$1` and scale to `1.2`
- Added scale to `IconArrowUp`, `IconDeviceReset`, and `IconAccount`
> Aligned menu icons on desktop

- packages/app/features/activity/ActivityDetails.tsx
- packages/app/features/home/TokenActivityRow.tsx
- packages/app/utils/activity.ts
The PR enhances the activity details and token activity row by adding liquidity pools to the useEventNameFromActivity and usePhraseFromActivity functions.
- Added liquidityPools to useEventNameFromActivity and usePhraseFromActivity
- Updated ActivityDetails and TokenActivityRow to use the new functions
- Improved event name and phrase handling for activities
> Fixed 'withdraw' word show for trades instead of trade in activity

- packages/snaplet/bin/seed.ts
Added back swap routers part of seeder, including mainnet client and hex to bytes conversion.
- Added swap routers to seeder
- Imported mainnet client and hex to bytes conversion utility
- Updated seed function to include swap routers
> Added back swap routers part of seeder

- packages/app/features/account/settings/layout.web.tsx
The PR introduces a new layout for settings pages, with separate layouts for desktop and mobile devices, using media queries to determine the layout.
- Added desktop and mobile settings layouts
- Used media query to determine layout
- Created separate components for desktop and mobile layouts
> Put settings pages behind bottom nav bar

- packages/app/components/BottomTabBar/BottomNavBar.tsx
The PR introduces a feature to hide the bottom navigation bar when scrolling down, enhancing the user experience.
- Hides bottom nav bar when scrolling down
- Adds scroll direction detection
- Animates nav bar hide/show
> Hid bottom nav bar when scrolling down

- packages/app/features/swap/summary/__snapshots__/screen.test.tsx.snap
- packages/app/features/swap/summary/screen.tsx
Fixed edit button functionality on trade page by adjusting button styles and adding hitSlop.
- Added hitSlop to EditButton for better press detection
- Removed border radius from EditButton
> Fixed edit button not always working on trade page

- packages/app/features/account/components/editProfile/screen.tsx
- packages/app/features/account/settings/personal-info.tsx
Fixed settings edit pages width on desktop by adding formProps to limit maxWidth.
- Added formProps to EditProfileForm
- Added formProps to PersonalInfoScreen
- Set maxWidth to 100% for screens greater than small
> Fixed settings edit pages width on desktop

- packages/app/features/home/HomeQuickActions.tsx
- packages/app/features/home/TokenDetails.test.tsx
- packages/app/features/home/TokenDetails.tsx
- packages/app/features/home/screen.tsx
The PR introduces a new "Send" action to the HomeQuickActions component, 
which is conditionally displayed based on the user's sending unlock status and 
screen size. The TokenDetails component now also considers the sending unlock 
status when rendering the HomeQuickActions.
- Added a new "Send" action to HomeQuickActions
- Introduced conditional rendering of HomeQuickActions in TokenDetails
- Updated HomeBody to animate HomeQuickActions and TokenBalanceList
- Removed redundant code in HomeBody
- Added useIsSendingUnlocked hook to TokenDetails
> Aligned desktop home page with mobile

- packages/app/components/FormFields/CoinField.tsx
- packages/app/components/SearchBar.tsx
- packages/app/components/sidebar/HomeSideBar.tsx
- packages/app/features/account/screen.tsx
- packages/app/features/account/settings/SettingsNavLink.tsx
- packages/app/features/deposit/components/DepositOptionButton.tsx
- packages/app/features/home/HomeQuickActions.tsx
- packages/app/features/home/TokenActivityRow.tsx
- packages/app/features/home/TokenBalanceList.tsx
- packages/app/features/swap/form/screen.tsx
- packages/app/utils/useHoverStyles.ts
Fixed hover styles type issue by removing ts-expect-error comments and updating background type in useHoverStyles.
- Removed ts-expect-error comments for hover styles
- Updated background type in useHoverStyles to `rgba(${string})`
> Fixed hover styles type issue

- apps/expo/package.json
- packages/app/utils/getRpId.ts
- yarn.lock
- **fix(app): recalculate the rpId when requesting passkey**
- **fix(app): check if window is defined**
- **fix: drop react-native-passkeys and used patched version**
> fix: drop react-native-passkeys and used patched version

- packages/app/features/sendpot/hooks/useDidUserBuyTicket.tsx
If you didn't buy a ticket on the current round but did previously, it would still continue to show the risk dialog.
> Fix Disclaimer dialog for Megapot

- apps/next/pages/account/affiliate.tsx
- packages/app/features/account/components/AccountHeader.tsx
- packages/app/features/account/components/AccountLinks.tsx
- packages/app/features/affiliate/screen.tsx
The PR updates the referral system to use the term "Friends" instead of "Affiliates". 
It changes the title, meta description, and subheader of the affiliate page, 
and updates the text of buttons and links to reflect the new terminology.
- Update title and meta description of affiliate page
- Change subheader to "View invited friends and track activity"
- Update button text to "Invite Friends"
- Update link text to "Friends"
> Changed referral texts

- packages/app/features/profile/screen.tsx
The PR updates the activity spinner position and the useTransactionEntryDate hook to consider the 'sent' status.
- Update activity spinner position based on 'sent' status
- Modify useTransactionEntryDate hook to accept 'sent' parameter
- Align spinner with 'flex-end' when 'sent' is true
> Fix activity spinner position

- packages/app/components/ReferralLink.tsx
- packages/app/features/account/components/AccountHeader.tsx
The PR updates the ReferralLink component to display the send ID when no send tags are available. It also modifies the AccountHeader component to use the confirmed tags.
- Added send ID display to ReferralLink component
- Updated AccountHeader component to use confirmed tags
- Modified referral code logic in ReferralLink component
> Added send id to account page when no send tags

- apps/next/pages/account/index.tsx
- packages/app/components/TopNav.tsx
The PR introduces a new feature to hide account and activity buttons in the navigation bar on the account page.
- Hide account and activity buttons in nav on account page
- Add hideRightActions prop to TopNav component
- Update HomeLayout to use new TopNav prop
> Hide account and activity buttons in nav on activity page

- packages/app/features/send/screen.tsx
- packages/app/features/send/suggestions/SendSuggestion.types.ts
- packages/app/features/send/suggestions/SendSuggestions.tsx
- packages/app/features/send/suggestions/useFavouriteSenders.ts
- packages/app/features/send/suggestions/useRecentSenders.ts
- packages/app/features/send/suggestions/useTodayBirthdaySenders.ts
- supabase/database-generated.types.ts
- supabase/migrations/20250523225150_today_birthday_senders.sql
The PR introduces a new feature to display today's birthday senders in the send screen. It includes a new query to fetch users with birthdays today and a new component to display the suggestions.
- Added today birthday senders query
- Introduced new SendSuggestions component
- Updated useFavouriteSenders and useRecentSenders to return SendSuggestionsQueryResult
- Created new useTodayBirthdaySenders hook
- Modified SendScreen to include today birthday senders
> Today birthday senders

- apps/next/utils/normalizeRedirectUrl.test.ts
- apps/next/utils/normalizeRedirectUrl.ts
- apps/next/utils/userProtected.ts
The PR enhances the `normalizeRedirectUrl` function to preserve query parameters and handle complex URLs during normalization.
- Enhance `normalizeRedirectUrl` to preserve query parameters
- Handle complex URLs during normalization
- Update tests for `normalizeRedirectUrl`
- Fix redirect URL handling in `userProtectedGetSSP`
> fix: fix normalizeRedirectUrl to preserve query parameters

- supabase/migrations/20250526225150_today_birthday_restrictions.sql
Added a new function `today_birthday_senders` to filter users who have paid tags, minimum balance, and have sent SEND tokens at least once in the current month.
- Added a new SQL function to filter users
- Implemented restrictions for today's birthday feed
- Selected users with paid tags and minimum balance
- Ordered results by send score
> Added today birthday feed restrictions

- packages/app/features/send/suggestions/SendSuggestions.tsx
- supabase/migrations/20250526225151_favorite_senders_changes.sql
The PR introduces improvements to the favorites feed, including a SQL function to retrieve favorite senders based on interaction counts and send scores. It also fixes a bug where users see themselves in the feed.
- Improved favorite senders query
- Fixed bug where users see themselves in feed
- Added security definer to SQL function
- Limited favorite senders to top 30 by interaction count and top 10 by send score
> Favorites feed improvements

- supabase/migrations/20250528225151_improve_top_senders.sql
Improved the top senders query by changing the send score calculation and ordering recent distributions by number.
- Improved top senders query
- Changed send score calculation to use weight of send_ceiling
- Ordered recent distributions by number
> Improved top senders query

- packages/app/features/home/InvestmentsBalanceCard.tsx
`toSorted()` is not supported in Hermes JavaScript engine on iOS, causing runtime errors despite being available in modern browsers and Node.js.
Replace `array.toSorted()` with `[...array].sort()` which provides identical functionality:
- Creates a new sorted array without mutating the original
- Works across all JavaScript environments
- More explicit about creating a new array
- ✅ Replaced `toSorted()` calls with spread operator + `sort()`
- ✅ Maintains same sorting behavior and immutability
- ✅ No breaking changes to component logic
```diff
- const sortedData = items.toSorted((a, b) => a.value - b.value);
+ const sortedData = [...items].sort((a, b) => a.value - b.value);
```
**Impact**: Fixes iOS compatibility issue while maintaining identical functionality.
> Changed toSorted to spread and sort

- supabase/config.toml
- supabase/database-generated.types.ts
- supabase/migrations/20250614002319_patch_security_send_score_views.sql
- supabase/schemas/distributions.sql
- supabase/schemas/send_earn.sql
- supabase/schemas/send_scores.sql
- supabase/schemas/views/send_scores.sql
- supabase/tests/distribution_hodler_addresses_test.sql
Improved security and performance of Send Scores functionality by moving the materialized view to the private schema and implementing a secure access pattern.
- Moved `send_scores_history` from public to private schema to improve security
- Created a new `get_send_scores_history()` function with proper security definer settings
- Added a new `get_send_score()` function in the private schema to calculate scores efficiently
- Updated the `send_scores` view to use the new function-based approach
- Refactored verification triggers to use the private function instead of querying views
- Added proper permission controls to all related functions and views
- Added a new schema file `send_scores.sql` to organize the Send Scores functionality
1. Run the migration to apply the changes
2. Verify that …
> Modify send score row security

- apps/next/next.config.js
- packages/app/features/account/components/ShareProfileDialog.tsx
- packages/app/package.json
- yarn.lock
The PR introduces changes to share a user's profile QR code, replacing the `qrcode` library with `react-native-qrcode-svg` and updating the `ShareProfileDialog` component.
- Replaced `qrcode` library with `react-native-qrcode-svg`
- Updated `ShareProfileDialog` component to use `QRCodeSVG`
- Removed `useEffect` hook for generating QR code
- Added `react-native-qrcode-svg` to dependencies
> Native: share profile qr code

- supabase/database-generated.types.ts
- supabase/migrations/20250716111120_add_send_id_to_get_friends.sql
- supabase/schemas/referrals.sql
Added `send_id` to the `get_friends` function in the Supabase database.
- Added `send_id` to the `get_friends` function return type
- Updated the `get_friends` function to include `send_id` in the query results
- Modified the `get_friends` function to return `send_id` as an integer
> Added send id to get friends

- packages/app/features/account/sendtag/checkout/checkout-utils.ts
- packages/app/features/activity/utils/useActivityFeed.ts
- packages/app/features/earn/deposit/hooks/index.ts
- packages/app/features/earn/hooks/index.ts
- packages/app/features/earn/rewards/hooks/index.ts
- packages/app/features/earn/utils/useEarnActivityFeed.ts
- packages/app/features/home/RewardsCard.tsx
- packages/app/features/home/utils/useTokenActivityFeed.ts
- packages/app/utils/distributions.ts
- packages/app/utils/referrer.ts
- packages/app/utils/useProfileLookup.ts
- packages/app/utils/useReferrer.ts
Main goal is to improve performance and reduce API calls by removing unnecessary supabase object from query keys
- Removed supabase from query keys in sendtagCheckoutReceiptsQueryOptions
- Removed supabase from query keys in useActivityFeed
- Removed supabase from query keys in useReferrerVault
- Removed supabase from query keys in sendEarnBalancesQueryOptions
- Removed supabase from query keys in sendEarnBalancesTimelineQueryOptions
- Removed supabase from query keys in sendEarnBalancesAtBlockQueryOptions
> Removed supabase from query keys

- apps/expo/app/(tabs)/_layout.tsx
Changed tabs order in the native app to align with the web version.
- Updated tab icons and titles
- Swapped 'Explore' and 'Activity' tab positions
> Native: changed tabs order to be aligned with web

- apps/expo/app/(tabs)/_layout.tsx
The PR enhances the tab bar detection by adding a new condition to animate the tab bar only when the user scrolls down or up and the first segment is '(tabs)'.
- Added useSegments hook from expo-router
- Introduced a new condition to animate the tab bar
- Updated the useEffect hook to handle the new condition
- Added a ref to store the previous scroll direction
> Native: fixed hiding tab bar detection

- apps/next/utils/seo.ts
- Add default constants for SEO image, Twitter handles, and image dimensions
- Add optional parameters for OpenGraph type, image dimensions, Twitter handle, and alt text
- Improve type safety with explicit OpenGraph type options
- Add comprehensive JSDoc documentation with usage examples
- Ensure backwards compatibility by keeping 'profile' as default type
> refactor(seo): enhance buildSeo utility with flexible parameters and better defaults

- apps/next/pages/404.tsx
- apps/next/pages/account/index.tsx
- apps/next/pages/activity.tsx
- apps/next/pages/leaderboard.tsx
- apps/next/pages/send/index.tsx
- Convert 404 page from Head to NextSeo with PAGE_TITLES and PAGE_DESCRIPTIONS
- Convert leaderboard page from Head to NextSeo with consistent constants
- Update account, send, and activity pages to use SEO constants
- Eliminate hardcoded titles and descriptions in favor of centralized constants
- Ensure consistent SEO patterns across simple pages
> refactor(seo): standardize simple pages to use SEO constants

- apps/expo/app/index.tsx
The PR introduces a feature to clear queries after sign out in the native app.
- Add useFocusEffect to clear queries on sign out
- Import useQueryClient from @tanstack/react-query
- Use queryClient.clear() to remove cached queries
> Native: clear queries after sign out

- packages/app/features/auth/sign-up/screen.tsx
- packages/app/utils/useIsScreenFocused.native.ts
- packages/app/utils/useIsScreenFocused.ts
The PR introduces a new hook `useIsScreenFocused` to track screen focus and updates the `SignUpScreen` to use it, fixing weird auth screens redirection.
- Added `useIsScreenFocused` hook
- Updated `SignUpScreen` to use `useIsScreenFocused`
- Fixed auth screens redirection
> Native: fix weird auth screens redirection

- packages/app/components/icons/IconLinkInBio.tsx
- packages/app/features/account/components/linkInBio/screen.tsx
- packages/app/utils/useLinkInBioMutation.ts
- packages/snaplet/.snaplet/dataModel.json
- packages/snaplet/.snaplet/snaplet-client.d.ts
- packages/snaplet/.snaplet/snaplet.d.ts
- packages/snaplet/snaplet.config.ts
- supabase/database-generated.types.ts
- supabase/migrations/20250727064321_add_new_links_in_bio.sql
- supabase/schemas/link_in_bio.sql
- supabase/schemas/referrals.sql
- supabase/schemas/types.sql
Added new social media platforms to the Link in Bio feature and improved error handling.
- Added 5 new social media platforms to Link in Bio:
- Facebook
- OnlyFans
- WhatsApp
- Snapchat
- Twitch
- Added error display in the LinkInBioScreen component to show validation errors
- Improved error handling for invalid link handles with a specific error message
- Updated database schema with a migration to support the new platforms
- Fixed profile lookup functions to properly handle the link_in_bio data structure
1. Navigate to the Link in Bio section in the account settings
2. Try adding links for the new platforms (Facebook, OnlyFans, WhatsApp, Snapchat, Twitch)
3. Test error handling by entering invalid handles
4. Verify that error messages are displayed correctly
This change expands the …
> Add new links in bio

- apps/expo/package.json
- packages/ui/package.json
- yarn.lock
The PR updates the `expo-blur` version to `~14.0.3` in two package.json files.
- Update `expo-blur` version to `~14.0.3`
- Modify `apps/expo/package.json` and `packages/ui/package.json`
> Native: fix expo blur version

- packages/app/provider/index.tsx
The `useCoins` hook was throwing "useCoins must be used within a CoinsProvider" errors specifically on Android when navigating to the send form (`/send/form`). This occurred in the `TokenBalance` component inside `CoinFieldItem`, which is rendered within a Tamagui Sheet/Portal.
**Root Cause:** The `CoinsProvider` was positioned after `TamaguiProvider` in the provider chain. Since Tamagui portals (used by Sheet components) render their content outside the normal React tree, components inside portals couldn't access the `CoinsProvider` context.
1. User navigates to send form
2. `CoinField` component renders inside a Tamagui Sheet (portal)
3. `TokenBalance` component calls `useCoins()` hook
4. Portal content is rendered outside the provider tree
5. Context is `undefined` → Error thrown
Moved …
> Fixed order of providers

- packages/app/features/account/components/editProfile/screen.tsx
- packages/app/features/account/components/personalInfo/screen.tsx
- packages/app/features/auth/onboarding/screen.tsx
- packages/app/features/auth/sign-up/screen.tsx
Fixed forms height for Android devices by setting minHeight, height, and flex to 'auto' and 0 respectively.
- Fixed forms height for Android devices
- Removed hardcoded height for YStack components
- Updated formProps for Android devices
> Native: fixed forms height for android

- packages/app/features/swap/form/RiskDialog/SwapRiskDialog.tsx
- packages/app/features/swap/form/screen.tsx
The PR introduces minor UI fixes to the trades screen for Android, adjusting the label line height and removing the flex property from an XStack component.
- Adjusted label line height in SwapRiskDialog
- Removed flex property from XStack in Slippage component
> Native: trades screen fixes for android

- apps/expo/components/layout/ScreenContainer.tsx
- apps/expo/components/layout/TabScreenContainer.tsx
- packages/app/components/SearchBar.tsx
- packages/app/features/activity/RecentActivityFeed.native.tsx
- packages/app/features/affiliate/screen.native.tsx
- packages/app/features/earn/earnings/screen.tsx
- packages/app/features/earn/rewards/screen.tsx
- packages/app/features/home/TokenActivityFeed.native.tsx
- packages/app/features/send-token-upgrade/screen.tsx
- packages/app/features/send/confirm/screen.tsx
- packages/ui/src/components/FormWrapper.native.tsx
Fixed issue with disappearing elevation on Android while scrolling by setting overScrollMode to 'never' in various ScrollView components.
- Fixed elevation issue on Android
- Updated overScrollMode in ScrollView components
- Removed elevation from Card components
> Native: fixed issue with disappearing elevation on android while scrolling

- packages/app/features/activity/RecentActivityFeed.native.tsx
- packages/app/features/home/TokenActivityFeed.native.tsx
- packages/app/features/home/TokenActivityRow.tsx
Fixed random gaps between activity rows on Android by adding border width and color.
- Added border width and color to XStack components
- Updated TokenActivityRow with border width and color
> Native: fixed some weird random gaps between activity rows on android

- apps/next/pages/_app.tsx
- packages/app/features/home/TokenChartSection.web.tsx
- packages/app/features/home/TokenDetails.tsx
- packages/app/features/home/charts/shared/components/ChartCardSection.tsx
- packages/app/features/home/charts/shared/components/ChartExtremeLabels.tsx
- packages/app/features/home/charts/shared/components/ChartLineSection.tsx
- packages/app/features/home/charts/shared/components/TimeframeTabs.tsx
- packages/app/features/home/charts/shared/timeframes.ts
- packages/app/features/home/charts/shared/useScrubState.native.ts
- packages/app/features/home/charts/shared/useScrubState.web.ts
- packages/app/features/home/charts/shared/useTokenChartData.ts
- packages/app/features/home/screen.tsx
- packages/app/utils/coin-gecko/index.native.tsx
- packages/app/utils/coin-gecko/index.tsx
- packages/app/utils/useTokenPrices.ts
- packages/ui/src/components/AnimatedCharts/charts/linear/ChartDot.web.tsx
- packages/ui/src/components/AnimatedCharts/charts/linear/ChartPath.tsx
- packages/ui/src/components/AnimatedCharts/charts/linear/ChartPath.web.tsx
Refactored the token chart component to improve code organization and add web support for chart scrubbing.
- Restructured the token chart code by extracting reusable components into separate files
- Created platform-specific implementations for chart scrubbing (native and web)
- Added web-specific implementations for `ChartPath` and `ChartDot` components
- Improved chart styling and layout consistency across platforms
- Added gesture handling for web to enable chart scrubbing without Reanimated worklets
- Imported required gesture handler and reanimated packages in Next.js app
- Extracted timeframe utilities into a shared module
1. Run the app on both web and native platforms
2. Navigate to a token detail page with a price chart
3. Test chart scrubbing on both platforms:
- On native: Use …
> no worklets for chart on web

- docs/design/investments-body.md
- packages/api/src/routers/_app.ts
- packages/api/src/routers/coingecko/router.ts
- packages/app/components/ProfileTopNav.tsx
- packages/app/data/coins.ts
- packages/app/features/auth/components/Carousel.native.tsx
- packages/app/features/home/InvestmentBalanceList.tsx
- packages/app/features/home/InvestmentsBalanceCard.tsx
- packages/app/features/home/TokenAbout.tsx
- packages/app/features/home/TokenChartSection.tsx
- packages/app/features/home/TokenChartSection.web.tsx
- packages/app/features/home/TokenDetails.skiptest.tsx
- packages/app/features/home/TokenDetails.tsx
- packages/app/features/home/TokenDetailsHeader.tsx
- packages/app/features/home/TokenKeyMetrics.tsx
- packages/app/features/home/charts/shared/components/ChartCardSection.tsx
- packages/app/features/home/charts/shared/timeframes.ts
- packages/app/features/home/charts/shared/useTokenChartData.ts
- packages/app/features/home/screen.tsx
- packages/app/provider/coins/CoinsProvider.tsx
- packages/app/utils/api.native.ts
- packages/app/utils/api.ts
- packages/app/utils/coin-gecko/index.native.tsx
- packages/app/utils/coin-gecko/index.tsx
- packages/app/utils/useTokenPrices.ts
Improved market data fetching for investments with adaptive polling, automatic fallbacks, and CDN caching optimizations.
- Added a new CoinGecko router in the API with automatic fallback from Pro to Free API
- Implemented `useTokensMarketData` to fetch market data with adaptive polling based on network conditions
- Added automatic fallback from CoinGecko to DexScreener for token prices when CoinGecko returns errors
- Optimized API requests to use GET for public endpoints to enable CDN caching
- Improved the TokenDetails screens to use the new data fetching hooks
- Enhanced the InvestmentsBalanceCard to use 7-day percentage changes with fallback to 24h
- Fixed the carousel progress animation in the auth flow
1. Navigate to the Investments tab and verify that market data loads correctly
2. …
> Use coingecko pro

- apps/expo/components/layout/ScreenContainer.tsx
- packages/app/features/home/charts/shared/components/ChartLineSection.tsx
- packages/app/features/home/docs/TokenCharts.md
- packages/ui/src/components/AnimatedCharts/charts/linear/ChartPath.tsx
- packages/ui/src/components/AnimatedCharts/charts/linear/ChartPath.web.tsx
- packages/ui/src/gestures/ScrollGestureContext.tsx
Why:
Vertical page scroll was being intercepted when the initial touch
started on the chart. Requiring a 500ms hold before activating chart
scrubbing lets normal vertical scrolling pass through while still
allowing deliberate chart interactions. Web adds a subtle focused
indicator (stroke width bump) during active scrubbing; native keeps the
existing focus animation. Behavior is gated on both platforms and
resets on end/cancel.
References:
- packages/ui/src/components/AnimatedCharts/charts/linear/ChartPath.web.tsx
(pointer-event gating with touch-action: pan-y, preventDefault only
when active)
- packages/ui/src/components/PendingIndicatorBar.tsx
(setTimeout/clearTimeout lifecycle pattern used for reliable timers)
- packages/ui/src/components/AnimatedCharts/charts/linear/ChartPath.tsx …
> Charts: require 500ms hold to scrub

- docs/send-scores.md
- supabase/migrations/20250920073031_trigger_on_new_distribution.sql
- supabase/schemas/distributions.sql
- supabase/schemas/send_token_transfers.sql
Why:
Ensure only one transaction per previous distribution attempts the
refresh of private.send_scores_history. All other transactions skip MV
access entirely so other triggers are not delayed and commit latency is
minimized. This reduces redundant refresh work and limits commit-time
contention while keeping the logic inside the deferred trigger.
Test plan:
- Verify function compiles and trigger remains DEFERRABLE INITIALLY
DEFERRED.
- Concurrency smoke: two sessions try
SELECT pg_try_advisory_xact_lock(918273645, <prev_id>::int);
Expect exactly one true; the other false.
- Insert transfers in a new distribution window under concurrency; check
that only one commit runs the refresh (others skip), and no errors are
raised.
> Gate MV refresh with per-distribution advisory lock

- supabase/tests/refresh_send_scores_trigger_test.sql
Why: The test mirrors the trigger’s own one-time guard by asserting the tx-local GUC (vars.refresh_scores_on_distribution_change_done) transitions from unset -> '1' after the first flush and remains '1' after the second, proving single execution per transaction. We also target the named constraint in SET CONSTRAINTS for precision and keep isolation via savepoints plus outer ROLLBACK.   
Test plan: - Run just this file: supabase test db supabase/tests/refresh_send_scores_trigger_test.sql Expect 3 passing assertions (unset -> '1' -> '1'). - Optionally, run the full suite to verify no cross-test contamination.
> tests: assert refresh via tx-local guard flag

- docs/swaps.md
- packages/api/src/routers/swap/router.ts
- packages/api/src/routers/swap/types.ts
- packages/app/features/swap/form/screen.tsx
Why:
- Deliver accurate, responsive dual-input swaps with fewer requests and no rerender loops.
- Ensure the summary screen always consumes a fresh forward route.
API (router):
- Add estimateAmountInFromAmountOut({ tokenIn, tokenOut, amountOut }) → { estimatedAmountIn, amountInUsd, amountOutUsd } using a single forward probe and linear scaling.
- Use coin registry for decimals (no on-chain reads); keep debug tracing for probe/initial/scaled and errors.
App (form):
- EXACT_IN: use fetchSwapRoute; gate query to quoteSide === 'EXACT_IN'.
- EXACT_OUT: use estimator; set inAmount via a debounced writer; USDs from estimator; skip inAmount writes in onFormChange to avoid duplicate forward queries.
- Validation: when EXACT_OUT, block submit and surface an error if estimatedAmountIn exceeds the …
> feat: swaps dual input

- apps/next/pages/earn/index.tsx
- packages/app/features/earn/screen.tsx
Why:
Simplifies the Earn page to focus on balances and active deposits. Removes
the promo "Learn how it works" hero card and its external image asset to
reduce UI complexity and avoid network dependencies. Also drops unused
imports (Image, LinearGradient, Link, IconArrowRight) and related layout
code. The Next.js page now renders EarnScreen without props.
Test plan:
- Web (Next): Start the dev server and open /earn
- Expect: Only the account/details section renders; no hero/learn card.
- No console errors; EarnScreen takes no images prop.
- Type check/build: project compiles without missing imports or props.
- Mobile (optional): Open the Earn screen; UI renders and navigation works.
> earn: remove LearnSection and images prop

- packages/app/provider/auth/AuthProvider.native.tsx
The PR introduces memoization to the AuthProvider component using the `useMemo` hook, which optimizes the computation of the context value.
- Added `useMemo` hook to memoize context value
- Removed redundant conditional statements
- Improved code readability
> Native: memoize auth provider

- packages/app/utils/usePush.native.ts
- packages/app/utils/usePush.ts
- packages/app/utils/useReplace.native.ts
- packages/app/utils/useReplace.ts
Added very simple platform specific hooks for navigation as solito is not doing great job at memoizing push and replace functions on native. Direct exports from expo-router are memoized by expo.
> Native: added platform specific hooks for navigation

- packages/app/features/account/components/AccountHeader.tsx
Fixed double URL in share functionality by removing redundant URL parameter.
- Removed redundant URL parameter in share functionality
> Fixed double url in share

- packages/app/features/home/InvestmentsBalanceCard.tsx
- packages/app/features/home/TokenDetailsHeader.tsx
- packages/app/features/home/screen.tsx
- packages/app/features/home/utils/__tests__/calculatePercentageChange.test.ts
- packages/app/features/home/utils/calculatePercentageChange.ts
Why:
Inline percentage-based USD delta calculations were duplicated and
error-prone. This refactor extracts a clear utility that computes the
actual dollar change using the previous-value method (previous =
current / (1 + pct/100)), and updates call sites to use it.
Changes:
- Extract calculatePercentageChange utility.
- Replace inline calculations in Home/Investments components.
- Add comprehensive unit tests covering positive/negative/edge cases.
Affected files:
- packages/app/features/home/InvestmentsBalanceCard.tsx
- packages/app/features/home/TokenDetailsHeader.tsx
- packages/app/features/home/screen.tsx
- packages/app/features/home/utils/__tests__/calculatePercentageChange.test.ts
- packages/app/features/home/utils/calculatePercentageChange.ts
Test plan:
- Run app tests:
yarn …
> refactor: extract percent change util + tests

- supabase/database-generated.types.ts
- supabase/migrations/20250930143101_add_is_verified_to_profile_lookup.sql
- supabase/schemas/referrals.sql
Why:
Mirror tag_search’s is_verified computation in profile_lookup so UI can
surface verification consistently. Append the field to the end of
profile_lookup_result to minimize breakage. Update public.referrer alias
list to include the new field. Use ALTER TYPE in the migration to avoid
dropping dependent objects.
Test plan:
- Stop DB: yarn supabase stop
- Generate migration: yarn supabase migration:diff add_is_verified_to_profile_lookup
- Start DB: yarn supabase start
- Apply migration: npx supabase migration up
- Drift check: yarn supabase migration:diff changes# expect "No schema changes found"
> Add is_verified to profile_lookup

- packages/app/features/profile/screen.tsx
Why:
Mirror the existing SearchBar pattern for displaying a verified badge
(IconCheckCircle) when a profile is verified. This keeps the UI
consistent and uses the new profile_lookup.is_verified field.
Test plan:
- Open a verified user’s Profile and verify a check badge appears next
to their name
- Open an unverified user’s Profile and verify no badge is shown
> Show verified badge on Profile
